/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './parte-editar.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from 'ionic-angular/navigation/nav-params';
import * as import10 from '@angular/forms/src/form_builder';
import * as import11 from '../../service/parte.service';
import * as import12 from '../../service/varios.service';
import * as import13 from '@angular/core/src/metadata/view';
import * as import14 from '@angular/core/src/linker/component_factory';
import * as import15 from '@angular/core/src/linker/query_list';
import * as import16 from 'ionic-angular/components/toolbar/toolbar';
import * as import17 from 'ionic-angular/components/navbar/navbar';
import * as import18 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import19 from 'ionic-angular/components/content/content';
import * as import20 from '@angular/forms/src/directives/reactive_directives/form_group_directive';
import * as import21 from '@angular/forms/src/directives/ng_control_status';
import * as import22 from '@angular/forms/src/directives/reactive_directives/form_control_name';
import * as import23 from 'ionic-angular/components/input/input';
import * as import24 from 'ionic-angular/components/item/item';
import * as import25 from 'ionic-angular/components/label/label';
import * as import26 from 'ionic-angular/components/datetime/datetime';
import * as import27 from 'ionic-angular/components/button/button';
import * as import28 from 'angular2-signaturepad/signature-pad';
import * as import29 from 'ionic-angular/config/config';
import * as import30 from '@angular/core/src/linker/element_ref';
import * as import31 from 'ionic-angular/navigation/view-controller';
import * as import32 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import33 from 'ionic-angular/components/app/app';
import * as import34 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import35 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import36 from 'ionic-angular/util/keyboard';
import * as import37 from '@angular/core/src/zone/ng_zone';
import * as import38 from 'ionic-angular/components/tabs/tabs';
import * as import39 from '../../node_modules/ionic-angular/components/input/input.ngfactory';
import * as import40 from 'ionic-angular/util/form';
import * as import41 from 'ionic-angular/platform/platform';
import * as import42 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import43 from '../../node_modules/ionic-angular/components/datetime/datetime.ngfactory';
import * as import44 from 'ionic-angular/components/picker/picker';
import * as import45 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import46 from '../../node_modules/angular2-signaturepad/signature-pad.ngfactory';
import * as import47 from '@angular/forms/src/directives/ng_control';
import * as import48 from '@angular/forms/src/directives/control_value_accessor';
import * as import49 from '@angular/forms/src/directives/control_container';
import * as import50 from '@angular/core/src/security';
var renderType_ParteEditarComponent_Host:import0.RenderComponentType = (null as any);
class _View_ParteEditarComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ParteEditarComponent_0_4:import3.ParteEditarComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ParteEditarComponent_Host0,renderType_ParteEditarComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ParteEditarComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ParteEditarComponent_0_4 = new import3.ParteEditarComponent(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.NavParams),this.parentInjector.get(import10.FormBuilder),this.parentInjector.get(import11.ParteService),this.parentInjector.get(import12.VariosService));
    this._appEl_0.initComponent(this._ParteEditarComponent_0_4,[],compView_0);
    compView_0.create(this._ParteEditarComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.ParteEditarComponent) && (0 === requestNodeIndex))) { return this._ParteEditarComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._ParteEditarComponent_0_4.ngAfterViewInit(); } }
  }
}
function viewFactory_ParteEditarComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_ParteEditarComponent_Host === (null as any))) { (renderType_ParteEditarComponent_Host = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,[],{})); }
  return new _View_ParteEditarComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const ParteEditarComponentNgFactory:import14.ComponentFactory<import3.ParteEditarComponent> = new import14.ComponentFactory<import3.ParteEditarComponent>('ng-component',viewFactory_ParteEditarComponent_Host0,import3.ParteEditarComponent);
const styles_ParteEditarComponent:any[] = [];
var renderType_ParteEditarComponent:import0.RenderComponentType = (null as any);
class _View_ParteEditarComponent0 extends import1.AppView<import3.ParteEditarComponent> {
  _viewQuery_SignaturePad_0:import15.QueryList<any>;
  _el_0:any;
  _Header_0_3:import16.Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Navbar_2_4:import17.Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _ToolbarTitle_4_4:import18.ToolbarTitle;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import2.AppElement;
  _Content_9_4:import19.Content;
  _text_10:any;
  _el_11:any;
  _FormGroupDirective_11_3:import20.FormGroupDirective;
  _ControlContainer_11_4:any;
  _NgControlStatusGroup_11_5:import21.NgControlStatusGroup;
  _text_12:any;
  _el_13:any;
  /*private*/ _appEl_13:import2.AppElement;
  _FormControlName_13_4:import22.FormControlName;
  _NgControl_13_5:any;
  _NgControlStatus_13_6:import21.NgControlStatus;
  _TextInput_13_7:import23.TextInput;
  _text_14:any;
  _el_15:any;
  /*private*/ _appEl_15:import2.AppElement;
  _FormControlName_15_4:import22.FormControlName;
  _NgControl_15_5:any;
  _NgControlStatus_15_6:import21.NgControlStatus;
  _TextInput_15_7:import23.TextInput;
  _text_16:any;
  _el_17:any;
  /*private*/ _appEl_17:import2.AppElement;
  _Item_17_4:import24.Item;
  _ItemContent_17_5:import24.ItemContent;
  _query_Label_17_0:import15.QueryList<any>;
  _query_Button_17_1:import15.QueryList<any>;
  _query_Icon_17_2:import15.QueryList<any>;
  _text_18:any;
  _el_19:any;
  _Label_19_3:import25.Label;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  /*private*/ _appEl_22:import2.AppElement;
  _DateTime_22_4:import26.DateTime;
  _NG_VALUE_ACCESSOR_22_5:any[];
  _FormControlName_22_6:import22.FormControlName;
  _NgControl_22_7:any;
  _NgControlStatus_22_8:import21.NgControlStatus;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  /*private*/ _appEl_25:import2.AppElement;
  _Item_25_4:import24.Item;
  _ItemContent_25_5:import24.ItemContent;
  _query_Label_25_0:import15.QueryList<any>;
  _query_Button_25_1:import15.QueryList<any>;
  _query_Icon_25_2:import15.QueryList<any>;
  _text_26:any;
  _el_27:any;
  _Label_27_3:import25.Label;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  /*private*/ _appEl_30:import2.AppElement;
  _DateTime_30_4:import26.DateTime;
  _NG_VALUE_ACCESSOR_30_5:any[];
  _FormControlName_30_6:import22.FormControlName;
  _NgControl_30_7:any;
  _NgControlStatus_30_8:import21.NgControlStatus;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  /*private*/ _appEl_33:import2.AppElement;
  _Item_33_4:import24.Item;
  _ItemContent_33_5:import24.ItemContent;
  _query_Label_33_0:import15.QueryList<any>;
  _query_Button_33_1:import15.QueryList<any>;
  _query_Icon_33_2:import15.QueryList<any>;
  _text_34:any;
  _el_35:any;
  _Label_35_3:import25.Label;
  _text_36:any;
  _text_37:any;
  _el_38:any;
  /*private*/ _appEl_38:import2.AppElement;
  _DateTime_38_4:import26.DateTime;
  _NG_VALUE_ACCESSOR_38_5:any[];
  _FormControlName_38_6:import22.FormControlName;
  _NgControl_38_7:any;
  _NgControlStatus_38_8:import21.NgControlStatus;
  _text_39:any;
  _text_40:any;
  _el_41:any;
  /*private*/ _appEl_41:import2.AppElement;
  _Item_41_4:import24.Item;
  _ItemContent_41_5:import24.ItemContent;
  _query_Label_41_0:import15.QueryList<any>;
  _query_Button_41_1:import15.QueryList<any>;
  _query_Icon_41_2:import15.QueryList<any>;
  _text_42:any;
  _el_43:any;
  _Label_43_3:import25.Label;
  _text_44:any;
  _text_45:any;
  _el_46:any;
  /*private*/ _appEl_46:import2.AppElement;
  _FormControlName_46_4:import22.FormControlName;
  _NgControl_46_5:any;
  _NgControlStatus_46_6:import21.NgControlStatus;
  _TextArea_46_7:import23.TextArea;
  _text_47:any;
  _text_48:any;
  _el_49:any;
  /*private*/ _appEl_49:import2.AppElement;
  _Item_49_4:import24.Item;
  _ItemContent_49_5:import24.ItemContent;
  _query_Label_49_0:import15.QueryList<any>;
  _query_Button_49_1:import15.QueryList<any>;
  _query_Icon_49_2:import15.QueryList<any>;
  _text_50:any;
  _el_51:any;
  _Label_51_3:import25.Label;
  _text_52:any;
  _text_53:any;
  _el_54:any;
  /*private*/ _appEl_54:import2.AppElement;
  _FormControlName_54_4:import22.FormControlName;
  _NgControl_54_5:any;
  _NgControlStatus_54_6:import21.NgControlStatus;
  _TextInput_54_7:import23.TextInput;
  _text_55:any;
  _text_56:any;
  _el_57:any;
  /*private*/ _appEl_57:import2.AppElement;
  _Item_57_4:import24.Item;
  _ItemContent_57_5:import24.ItemContent;
  _query_Label_57_0:import15.QueryList<any>;
  _query_Button_57_1:import15.QueryList<any>;
  _query_Icon_57_2:import15.QueryList<any>;
  _text_58:any;
  _el_59:any;
  _el_60:any;
  /*private*/ _appEl_60:import2.AppElement;
  _Button_60_4:import27.Button;
  _text_61:any;
  _text_62:any;
  _el_63:any;
  /*private*/ _appEl_63:import2.AppElement;
  _SignaturePad_63_4:import28.SignaturePad;
  _text_64:any;
  _text_65:any;
  _text_66:any;
  _el_67:any;
  /*private*/ _appEl_67:import2.AppElement;
  _Item_67_4:import24.Item;
  _ItemContent_67_5:import24.ItemContent;
  _query_Label_67_0:import15.QueryList<any>;
  _query_Button_67_1:import15.QueryList<any>;
  _query_Icon_67_2:import15.QueryList<any>;
  _text_68:any;
  _el_69:any;
  /*private*/ _appEl_69:import2.AppElement;
  _Button_69_4:import27.Button;
  _text_70:any;
  _text_71:any;
  _el_72:any;
  /*private*/ _appEl_72:import2.AppElement;
  _Button_72_4:import27.Button;
  _text_73:any;
  _text_74:any;
  _text_75:any;
  _el_76:any;
  /*private*/ _appEl_76:import2.AppElement;
  _Item_76_4:import24.Item;
  _ItemContent_76_5:import24.ItemContent;
  _query_Label_76_0:import15.QueryList<any>;
  _query_Button_76_1:import15.QueryList<any>;
  _query_Icon_76_2:import15.QueryList<any>;
  _text_77:any;
  _el_78:any;
  _text_79:any;
  _text_80:any;
  _text_81:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_31:any;
  /*private*/ _expr_32:any;
  /*private*/ _expr_33:any;
  /*private*/ _expr_34:any;
  /*private*/ _expr_35:any;
  /*private*/ _expr_36:any;
  /*private*/ _expr_37:any;
  /*private*/ _expr_40:any;
  /*private*/ _expr_41:any;
  /*private*/ _expr_42:any;
  /*private*/ _expr_43:any;
  /*private*/ _expr_44:any;
  /*private*/ _expr_45:any;
  /*private*/ _expr_46:any;
  /*private*/ _expr_47:any;
  /*private*/ _expr_48:any;
  /*private*/ _expr_49:any;
  /*private*/ _expr_52:any;
  /*private*/ _expr_53:any;
  /*private*/ _expr_54:any;
  /*private*/ _expr_55:any;
  /*private*/ _expr_56:any;
  /*private*/ _expr_57:any;
  /*private*/ _expr_58:any;
  /*private*/ _expr_59:any;
  /*private*/ _expr_60:any;
  /*private*/ _expr_61:any;
  /*private*/ _expr_62:any;
  /*private*/ _expr_63:any;
  /*private*/ _expr_64:any;
  /*private*/ _expr_65:any;
  /*private*/ _expr_66:any;
  /*private*/ _expr_67:any;
  /*private*/ _expr_68:any;
  /*private*/ _expr_69:any;
  /*private*/ _expr_70:any;
  /*private*/ _expr_71:any;
  /*private*/ _expr_72:any;
  /*private*/ _expr_73:any;
  /*private*/ _expr_74:any;
  /*private*/ _expr_75:any;
  /*private*/ _expr_76:any;
  /*private*/ _expr_78:any;
  /*private*/ _expr_80:any;
  /*private*/ _expr_81:any;
  /*private*/ _expr_82:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ParteEditarComponent0,renderType_ParteEditarComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._viewQuery_SignaturePad_0 = new import15.QueryList<any>();
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import16.Header(this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import31.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import32.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import17.Navbar(this.parentInjector.get(import33.App),this.parentInjector.get(import31.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_4 = new import2.AppElement(4,2,this,this._el_4);
    var compView_4:any = import34.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ToolbarTitle_4_4 = new import18.ToolbarTitle(this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import16.Toolbar,(null as any)),this._Navbar_2_4);
    this._appEl_4.initComponent(this._ToolbarTitle_4_4,[],compView_4);
    this._text_5 = this.renderer.createText((null as any),'Editar Parte de trabajo',(null as any));
    compView_4.create(this._ToolbarTitle_4_4,[[].concat([this._text_5])],(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n    ',(null as any));
    compView_2.create(this._Navbar_2_4,[
      [],
      [],
      [],
      [].concat([
        this._text_3,
        this._el_4,
        this._text_6
      ]
      )
    ]
    ,(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_8 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_9 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this._appEl_9 = new import2.AppElement(9,(null as any),this,this._el_9);
    var compView_9:any = import35.viewFactory_Content0(this.viewUtils,this.injector(9),this._appEl_9);
    this._Content_9_4 = new import19.Content(this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import33.App),this.parentInjector.get(import36.Keyboard),this.parentInjector.get(import37.NgZone),this.parentInjector.get(import31.ViewController,(null as any)),this.parentInjector.get(import38.Tabs,(null as any)));
    this._appEl_9.initComponent(this._Content_9_4,[],compView_9);
    this._text_10 = this.renderer.createText((null as any),'\n\n    ',(null as any));
    this._el_11 = this.renderer.createElement((null as any),'form',(null as any));
    this._FormGroupDirective_11_3 = new import20.FormGroupDirective((null as any),(null as any));
    this._ControlContainer_11_4 = this._FormGroupDirective_11_3;
    this._NgControlStatusGroup_11_5 = new import21.NgControlStatusGroup(this._ControlContainer_11_4);
    this._text_12 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_11,'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_13,'formControlName','id');
    this.renderer.setElementAttribute(this._el_13,'hidden','');
    this._appEl_13 = new import2.AppElement(13,11,this,this._el_13);
    var compView_13:any = import39.viewFactory_TextInput0(this.viewUtils,this.injector(13),this._appEl_13);
    this._FormControlName_13_4 = new import22.FormControlName(this._ControlContainer_11_4,(null as any),(null as any),(null as any));
    this._NgControl_13_5 = this._FormControlName_13_4;
    this._NgControlStatus_13_6 = new import21.NgControlStatus(this._NgControl_13_5);
    this._TextInput_13_7 = new import23.TextInput(this.parentInjector.get(import29.Config),this.parentInjector.get(import40.Form),this.parentInjector.get(import24.Item,(null as any)),this.parentInjector.get(import33.App),this.parentInjector.get(import41.Platform),new import30.ElementRef(this._el_13),this.renderer,this._Content_9_4,this.parentInjector.get(import8.NavController,(null as any)),this._NgControl_13_5);
    this._appEl_13.initComponent(this._TextInput_13_7,[],compView_13);
    compView_13.create(this._TextInput_13_7,[],(null as any));
    this._text_14 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_11,'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_15,'formControlName','clienteid');
    this.renderer.setElementAttribute(this._el_15,'hidden','');
    this._appEl_15 = new import2.AppElement(15,11,this,this._el_15);
    var compView_15:any = import39.viewFactory_TextInput0(this.viewUtils,this.injector(15),this._appEl_15);
    this._FormControlName_15_4 = new import22.FormControlName(this._ControlContainer_11_4,(null as any),(null as any),(null as any));
    this._NgControl_15_5 = this._FormControlName_15_4;
    this._NgControlStatus_15_6 = new import21.NgControlStatus(this._NgControl_15_5);
    this._TextInput_15_7 = new import23.TextInput(this.parentInjector.get(import29.Config),this.parentInjector.get(import40.Form),this.parentInjector.get(import24.Item,(null as any)),this.parentInjector.get(import33.App),this.parentInjector.get(import41.Platform),new import30.ElementRef(this._el_15),this.renderer,this._Content_9_4,this.parentInjector.get(import8.NavController,(null as any)),this._NgControl_15_5);
    this._appEl_15.initComponent(this._TextInput_15_7,[],compView_15);
    compView_15.create(this._TextInput_15_7,[],(null as any));
    this._text_16 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_11,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_17,'class','item item-block');
    this._appEl_17 = new import2.AppElement(17,11,this,this._el_17);
    var compView_17:any = import42.viewFactory_Item0(this.viewUtils,this.injector(17),this._appEl_17);
    this._Item_17_4 = new import24.Item(this.parentInjector.get(import40.Form),this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_17),this.renderer);
    this._ItemContent_17_5 = new import24.ItemContent();
    this._query_Label_17_0 = new import15.QueryList<any>();
    this._query_Button_17_1 = new import15.QueryList<any>();
    this._query_Icon_17_2 = new import15.QueryList<any>();
    this._appEl_17.initComponent(this._Item_17_4,[],compView_17);
    this._text_18 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_19 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_19,'floating','');
    this._Label_19_3 = new import25.Label(this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_19),this.renderer,'',(null as any),(null as any),(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'Fecha',(null as any));
    this._text_21 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_22 = this.renderer.createElement((null as any),'ion-datetime',(null as any));
    this.renderer.setElementAttribute(this._el_22,'displayFormat','DD/MM/YYYY');
    this.renderer.setElementAttribute(this._el_22,'formControlName','fecha');
    this._appEl_22 = new import2.AppElement(22,17,this,this._el_22);
    var compView_22:any = import43.viewFactory_DateTime0(this.viewUtils,this.injector(22),this._appEl_22);
    this._DateTime_22_4 = new import26.DateTime(this.parentInjector.get(import40.Form),this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_22),this.renderer,this._Item_17_4,this.parentInjector.get(import44.PickerController,(null as any)));
    this._NG_VALUE_ACCESSOR_22_5 = [this._DateTime_22_4];
    this._FormControlName_22_6 = new import22.FormControlName(this._ControlContainer_11_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_22_5);
    this._NgControl_22_7 = this._FormControlName_22_6;
    this._NgControlStatus_22_8 = new import21.NgControlStatus(this._NgControl_22_7);
    this._appEl_22.initComponent(this._DateTime_22_4,[],compView_22);
    compView_22.create(this._DateTime_22_4,[],(null as any));
    this._text_23 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._query_Label_17_0.reset([this._Label_19_3]);
    this._Item_17_4.contentLabel = this._query_Label_17_0.first;
    compView_17.create(this._Item_17_4,[
      [],
      [].concat([this._el_19]),
      [].concat([
        this._text_18,
        this._text_21,
        this._text_23
      ]
      ),
      [].concat([this._el_22]),
      []
    ]
    ,(null as any));
    this._text_24 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._el_25 = this.renderer.createElement(this._el_11,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_25,'class','item item-block');
    this._appEl_25 = new import2.AppElement(25,11,this,this._el_25);
    var compView_25:any = import42.viewFactory_Item0(this.viewUtils,this.injector(25),this._appEl_25);
    this._Item_25_4 = new import24.Item(this.parentInjector.get(import40.Form),this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_25),this.renderer);
    this._ItemContent_25_5 = new import24.ItemContent();
    this._query_Label_25_0 = new import15.QueryList<any>();
    this._query_Button_25_1 = new import15.QueryList<any>();
    this._query_Icon_25_2 = new import15.QueryList<any>();
    this._appEl_25.initComponent(this._Item_25_4,[],compView_25);
    this._text_26 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_27 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_27,'floating','');
    this._Label_27_3 = new import25.Label(this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_27),this.renderer,'',(null as any),(null as any),(null as any));
    this._text_28 = this.renderer.createText(this._el_27,'Hora de inicio',(null as any));
    this._text_29 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_30 = this.renderer.createElement((null as any),'ion-datetime',(null as any));
    this.renderer.setElementAttribute(this._el_30,'displayFormat','HH:mm');
    this.renderer.setElementAttribute(this._el_30,'formControlName','horaini');
    this.renderer.setElementAttribute(this._el_30,'minuteValues','00,10,20,30,40,50');
    this._appEl_30 = new import2.AppElement(30,25,this,this._el_30);
    var compView_30:any = import43.viewFactory_DateTime0(this.viewUtils,this.injector(30),this._appEl_30);
    this._DateTime_30_4 = new import26.DateTime(this.parentInjector.get(import40.Form),this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_30),this.renderer,this._Item_25_4,this.parentInjector.get(import44.PickerController,(null as any)));
    this._NG_VALUE_ACCESSOR_30_5 = [this._DateTime_30_4];
    this._FormControlName_30_6 = new import22.FormControlName(this._ControlContainer_11_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_30_5);
    this._NgControl_30_7 = this._FormControlName_30_6;
    this._NgControlStatus_30_8 = new import21.NgControlStatus(this._NgControl_30_7);
    this._appEl_30.initComponent(this._DateTime_30_4,[],compView_30);
    compView_30.create(this._DateTime_30_4,[],(null as any));
    this._text_31 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._query_Label_25_0.reset([this._Label_27_3]);
    this._Item_25_4.contentLabel = this._query_Label_25_0.first;
    compView_25.create(this._Item_25_4,[
      [],
      [].concat([this._el_27]),
      [].concat([
        this._text_26,
        this._text_29,
        this._text_31
      ]
      ),
      [].concat([this._el_30]),
      []
    ]
    ,(null as any));
    this._text_32 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._el_33 = this.renderer.createElement(this._el_11,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_33,'class','item item-block');
    this._appEl_33 = new import2.AppElement(33,11,this,this._el_33);
    var compView_33:any = import42.viewFactory_Item0(this.viewUtils,this.injector(33),this._appEl_33);
    this._Item_33_4 = new import24.Item(this.parentInjector.get(import40.Form),this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_33),this.renderer);
    this._ItemContent_33_5 = new import24.ItemContent();
    this._query_Label_33_0 = new import15.QueryList<any>();
    this._query_Button_33_1 = new import15.QueryList<any>();
    this._query_Icon_33_2 = new import15.QueryList<any>();
    this._appEl_33.initComponent(this._Item_33_4,[],compView_33);
    this._text_34 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_35 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_35,'floating','');
    this._Label_35_3 = new import25.Label(this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_35),this.renderer,'',(null as any),(null as any),(null as any));
    this._text_36 = this.renderer.createText(this._el_35,'Hora de fin',(null as any));
    this._text_37 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_38 = this.renderer.createElement((null as any),'ion-datetime',(null as any));
    this.renderer.setElementAttribute(this._el_38,'displayFormat','HH:mm');
    this.renderer.setElementAttribute(this._el_38,'formControlName','horafin');
    this.renderer.setElementAttribute(this._el_38,'minuteValues','00,10,20,30,40,50');
    this._appEl_38 = new import2.AppElement(38,33,this,this._el_38);
    var compView_38:any = import43.viewFactory_DateTime0(this.viewUtils,this.injector(38),this._appEl_38);
    this._DateTime_38_4 = new import26.DateTime(this.parentInjector.get(import40.Form),this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_38),this.renderer,this._Item_33_4,this.parentInjector.get(import44.PickerController,(null as any)));
    this._NG_VALUE_ACCESSOR_38_5 = [this._DateTime_38_4];
    this._FormControlName_38_6 = new import22.FormControlName(this._ControlContainer_11_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_38_5);
    this._NgControl_38_7 = this._FormControlName_38_6;
    this._NgControlStatus_38_8 = new import21.NgControlStatus(this._NgControl_38_7);
    this._appEl_38.initComponent(this._DateTime_38_4,[],compView_38);
    compView_38.create(this._DateTime_38_4,[],(null as any));
    this._text_39 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._query_Label_33_0.reset([this._Label_35_3]);
    this._Item_33_4.contentLabel = this._query_Label_33_0.first;
    compView_33.create(this._Item_33_4,[
      [],
      [].concat([this._el_35]),
      [].concat([
        this._text_34,
        this._text_37,
        this._text_39
      ]
      ),
      [].concat([this._el_38]),
      []
    ]
    ,(null as any));
    this._text_40 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._el_41 = this.renderer.createElement(this._el_11,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_41,'class','item item-block');
    this._appEl_41 = new import2.AppElement(41,11,this,this._el_41);
    var compView_41:any = import42.viewFactory_Item0(this.viewUtils,this.injector(41),this._appEl_41);
    this._Item_41_4 = new import24.Item(this.parentInjector.get(import40.Form),this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_41),this.renderer);
    this._ItemContent_41_5 = new import24.ItemContent();
    this._query_Label_41_0 = new import15.QueryList<any>();
    this._query_Button_41_1 = new import15.QueryList<any>();
    this._query_Icon_41_2 = new import15.QueryList<any>();
    this._appEl_41.initComponent(this._Item_41_4,[],compView_41);
    this._text_42 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_43 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_43,'floating','');
    this._Label_43_3 = new import25.Label(this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_43),this.renderer,'',(null as any),(null as any),(null as any));
    this._text_44 = this.renderer.createText(this._el_43,'Trabajo realizado',(null as any));
    this._text_45 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_46 = this.renderer.createElement((null as any),'ion-textarea',(null as any));
    this.renderer.setElementAttribute(this._el_46,'formControlName','trabajorealizado');
    this.renderer.setElementAttribute(this._el_46,'textarea-autosize','');
    this._appEl_46 = new import2.AppElement(46,41,this,this._el_46);
    var compView_46:any = import39.viewFactory_TextArea0(this.viewUtils,this.injector(46),this._appEl_46);
    this._FormControlName_46_4 = new import22.FormControlName(this._ControlContainer_11_4,(null as any),(null as any),(null as any));
    this._NgControl_46_5 = this._FormControlName_46_4;
    this._NgControlStatus_46_6 = new import21.NgControlStatus(this._NgControl_46_5);
    this._TextArea_46_7 = new import23.TextArea(this.parentInjector.get(import29.Config),this.parentInjector.get(import40.Form),this._Item_41_4,this.parentInjector.get(import33.App),this.parentInjector.get(import41.Platform),new import30.ElementRef(this._el_46),this.renderer,this._Content_9_4,this.parentInjector.get(import8.NavController,(null as any)),this._NgControl_46_5);
    this._appEl_46.initComponent(this._TextArea_46_7,[],compView_46);
    compView_46.create(this._TextArea_46_7,[],(null as any));
    this._text_47 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._query_Label_41_0.reset([this._Label_43_3]);
    this._Item_41_4.contentLabel = this._query_Label_41_0.first;
    compView_41.create(this._Item_41_4,[
      [],
      [].concat([this._el_43]),
      [].concat([
        this._text_42,
        this._text_45,
        this._text_47
      ]
      ),
      [].concat([this._el_46]),
      []
    ]
    ,(null as any));
    this._text_48 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._el_49 = this.renderer.createElement(this._el_11,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_49,'class','item item-block');
    this._appEl_49 = new import2.AppElement(49,11,this,this._el_49);
    var compView_49:any = import42.viewFactory_Item0(this.viewUtils,this.injector(49),this._appEl_49);
    this._Item_49_4 = new import24.Item(this.parentInjector.get(import40.Form),this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_49),this.renderer);
    this._ItemContent_49_5 = new import24.ItemContent();
    this._query_Label_49_0 = new import15.QueryList<any>();
    this._query_Button_49_1 = new import15.QueryList<any>();
    this._query_Icon_49_2 = new import15.QueryList<any>();
    this._appEl_49.initComponent(this._Item_49_4,[],compView_49);
    this._text_50 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_51 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_51,'floating','');
    this._Label_51_3 = new import25.Label(this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_51),this.renderer,'',(null as any),(null as any),(null as any));
    this._text_52 = this.renderer.createText(this._el_51,'Autorizado por:',(null as any));
    this._text_53 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_54 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_54,'formControlName','personafirma');
    this._appEl_54 = new import2.AppElement(54,49,this,this._el_54);
    var compView_54:any = import39.viewFactory_TextInput0(this.viewUtils,this.injector(54),this._appEl_54);
    this._FormControlName_54_4 = new import22.FormControlName(this._ControlContainer_11_4,(null as any),(null as any),(null as any));
    this._NgControl_54_5 = this._FormControlName_54_4;
    this._NgControlStatus_54_6 = new import21.NgControlStatus(this._NgControl_54_5);
    this._TextInput_54_7 = new import23.TextInput(this.parentInjector.get(import29.Config),this.parentInjector.get(import40.Form),this._Item_49_4,this.parentInjector.get(import33.App),this.parentInjector.get(import41.Platform),new import30.ElementRef(this._el_54),this.renderer,this._Content_9_4,this.parentInjector.get(import8.NavController,(null as any)),this._NgControl_54_5);
    this._appEl_54.initComponent(this._TextInput_54_7,[],compView_54);
    compView_54.create(this._TextInput_54_7,[],(null as any));
    this._text_55 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._query_Label_49_0.reset([this._Label_51_3]);
    this._Item_49_4.contentLabel = this._query_Label_49_0.first;
    compView_49.create(this._Item_49_4,[
      [],
      [].concat([this._el_51]),
      [].concat([
        this._text_50,
        this._text_53,
        this._text_55
      ]
      ),
      [].concat([this._el_54]),
      []
    ]
    ,(null as any));
    this._text_56 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._el_57 = this.renderer.createElement(this._el_11,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_57,'class','item item-block');
    this._appEl_57 = new import2.AppElement(57,11,this,this._el_57);
    var compView_57:any = import42.viewFactory_Item0(this.viewUtils,this.injector(57),this._appEl_57);
    this._Item_57_4 = new import24.Item(this.parentInjector.get(import40.Form),this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_57),this.renderer);
    this._ItemContent_57_5 = new import24.ItemContent();
    this._query_Label_57_0 = new import15.QueryList<any>();
    this._query_Button_57_1 = new import15.QueryList<any>();
    this._query_Icon_57_2 = new import15.QueryList<any>();
    this._appEl_57.initComponent(this._Item_57_4,[],compView_57);
    this._text_58 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_59 = this.renderer.createElement((null as any),'p',(null as any));
    this._el_60 = this.renderer.createElement(this._el_59,'button',(null as any));
    this.renderer.setElementAttribute(this._el_60,'ion-button','');
    this.renderer.setElementAttribute(this._el_60,'type','button');
    this._appEl_60 = new import2.AppElement(60,59,this,this._el_60);
    var compView_60:any = import45.viewFactory_Button0(this.viewUtils,this.injector(60),this._appEl_60);
    this._Button_60_4 = new import27.Button((null as any),'',this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_60),this.renderer);
    this._appEl_60.initComponent(this._Button_60_4,[],compView_60);
    this._text_61 = this.renderer.createText((null as any),'Firmar',(null as any));
    compView_60.create(this._Button_60_4,[[].concat([this._text_61])],(null as any));
    this._text_62 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_63 = this.renderer.createElement((null as any),'signature-pad',(null as any));
    this._appEl_63 = new import2.AppElement(63,57,this,this._el_63);
    var compView_63:any = import46.viewFactory_SignaturePad0(this.viewUtils,this.injector(63),this._appEl_63);
    this._SignaturePad_63_4 = new import28.SignaturePad(new import30.ElementRef(this._el_63));
    this._appEl_63.initComponent(this._SignaturePad_63_4,[],compView_63);
    compView_63.create(this._SignaturePad_63_4,[],(null as any));
    this._text_64 = this.renderer.createText((null as any),'    \n            ',(null as any));
    this._text_65 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._query_Label_57_0.reset([]);
    this._Item_57_4.contentLabel = this._query_Label_57_0.first;
    compView_57.create(this._Item_57_4,[
      [],
      [],
      [].concat([
        this._text_58,
        this._el_59,
        this._text_62,
        this._el_63,
        this._text_64,
        this._text_65
      ]
      ),
      [],
      []
    ]
    ,(null as any));
    this._text_66 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._el_67 = this.renderer.createElement(this._el_11,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_67,'class','item item-block');
    this._appEl_67 = new import2.AppElement(67,11,this,this._el_67);
    var compView_67:any = import42.viewFactory_Item0(this.viewUtils,this.injector(67),this._appEl_67);
    this._Item_67_4 = new import24.Item(this.parentInjector.get(import40.Form),this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_67),this.renderer);
    this._ItemContent_67_5 = new import24.ItemContent();
    this._query_Label_67_0 = new import15.QueryList<any>();
    this._query_Button_67_1 = new import15.QueryList<any>();
    this._query_Icon_67_2 = new import15.QueryList<any>();
    this._appEl_67.initComponent(this._Item_67_4,[],compView_67);
    this._text_68 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_69 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_69,'ion-button','');
    this.renderer.setElementAttribute(this._el_69,'type','submit');
    this._appEl_69 = new import2.AppElement(69,67,this,this._el_69);
    var compView_69:any = import45.viewFactory_Button0(this.viewUtils,this.injector(69),this._appEl_69);
    this._Button_69_4 = new import27.Button((null as any),'',this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_69),this.renderer);
    this._appEl_69.initComponent(this._Button_69_4,[],compView_69);
    this._text_70 = this.renderer.createText((null as any),'Enviar',(null as any));
    compView_69.create(this._Button_69_4,[[].concat([this._text_70])],(null as any));
    this._text_71 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_72 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_72,'color','danger');
    this.renderer.setElementAttribute(this._el_72,'ion-button','');
    this.renderer.setElementAttribute(this._el_72,'type','button');
    this._appEl_72 = new import2.AppElement(72,67,this,this._el_72);
    var compView_72:any = import45.viewFactory_Button0(this.viewUtils,this.injector(72),this._appEl_72);
    this._Button_72_4 = new import27.Button((null as any),'',this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_72),this.renderer);
    this._appEl_72.initComponent(this._Button_72_4,[],compView_72);
    this._text_73 = this.renderer.createText((null as any),'Cancelar',(null as any));
    compView_72.create(this._Button_72_4,[[].concat([this._text_73])],(null as any));
    this._text_74 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._query_Label_67_0.reset([]);
    this._Item_67_4.contentLabel = this._query_Label_67_0.first;
    compView_67.create(this._Item_67_4,[
      [],
      [],
      [].concat([
        this._text_68,
        this._el_69,
        this._text_71,
        this._el_72,
        this._text_74
      ]
      ),
      [],
      []
    ]
    ,(null as any));
    this._text_75 = this.renderer.createText(this._el_11,'\n        \n        ',(null as any));
    this._el_76 = this.renderer.createElement(this._el_11,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_76,'class','item item-block');
    this._appEl_76 = new import2.AppElement(76,11,this,this._el_76);
    var compView_76:any = import42.viewFactory_Item0(this.viewUtils,this.injector(76),this._appEl_76);
    this._Item_76_4 = new import24.Item(this.parentInjector.get(import40.Form),this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_76),this.renderer);
    this._ItemContent_76_5 = new import24.ItemContent();
    this._query_Label_76_0 = new import15.QueryList<any>();
    this._query_Button_76_1 = new import15.QueryList<any>();
    this._query_Icon_76_2 = new import15.QueryList<any>();
    this._appEl_76.initComponent(this._Item_76_4,[],compView_76);
    this._text_77 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_78 = this.renderer.createElement((null as any),'img',(null as any));
    this.renderer.setElementAttribute(this._el_78,'alt','firma');
    this._text_79 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._query_Label_76_0.reset([]);
    this._Item_76_4.contentLabel = this._query_Label_76_0.first;
    compView_76.create(this._Item_76_4,[
      [],
      [],
      [].concat([
        this._text_77,
        this._el_78,
        this._text_79
      ]
      ),
      [],
      []
    ]
    ,(null as any));
    this._text_80 = this.renderer.createText(this._el_11,'\n    ',(null as any));
    this._text_81 = this.renderer.createText((null as any),'\n    \n\n    ',(null as any));
    compView_9.create(this._Content_9_4,[
      [],
      [].concat([
        this._text_10,
        this._el_11,
        this._text_81
      ]
      ),
      []
    ]
    ,(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_11,'ngSubmit',this.eventHandler(this._handle_ngSubmit_11_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_11,'submit',this.eventHandler(this._handle_submit_11_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_11,'reset',this.eventHandler(this._handle_reset_11_2.bind(this)));
    this._expr_6 = import7.UNINITIALIZED;
    const subscription_0:any = this._FormGroupDirective_11_3.ngSubmit.subscribe(this.eventHandler(this._handle_ngSubmit_11_0.bind(this)));
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_20 = import7.UNINITIALIZED;
    this._expr_21 = import7.UNINITIALIZED;
    this._expr_22 = import7.UNINITIALIZED;
    this._expr_23 = import7.UNINITIALIZED;
    this._expr_24 = import7.UNINITIALIZED;
    this._expr_25 = import7.UNINITIALIZED;
    this._expr_26 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_22,'click',this.eventHandler(this._handle_click_22_0.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_22,'keyup.space',this.eventHandler(this._handle_keyup_space_22_1.bind(this)));
    this._expr_29 = import7.UNINITIALIZED;
    this._expr_30 = import7.UNINITIALIZED;
    this._expr_31 = import7.UNINITIALIZED;
    this._expr_32 = import7.UNINITIALIZED;
    this._expr_33 = import7.UNINITIALIZED;
    this._expr_34 = import7.UNINITIALIZED;
    this._expr_35 = import7.UNINITIALIZED;
    this._expr_36 = import7.UNINITIALIZED;
    this._expr_37 = import7.UNINITIALIZED;
    var disposable_5:Function = this.renderer.listen(this._el_30,'click',this.eventHandler(this._handle_click_30_0.bind(this)));
    var disposable_6:Function = this.renderer.listen(this._el_30,'keyup.space',this.eventHandler(this._handle_keyup_space_30_1.bind(this)));
    this._expr_40 = import7.UNINITIALIZED;
    this._expr_41 = import7.UNINITIALIZED;
    this._expr_42 = import7.UNINITIALIZED;
    this._expr_43 = import7.UNINITIALIZED;
    this._expr_44 = import7.UNINITIALIZED;
    this._expr_45 = import7.UNINITIALIZED;
    this._expr_46 = import7.UNINITIALIZED;
    this._expr_47 = import7.UNINITIALIZED;
    this._expr_48 = import7.UNINITIALIZED;
    this._expr_49 = import7.UNINITIALIZED;
    var disposable_7:Function = this.renderer.listen(this._el_38,'click',this.eventHandler(this._handle_click_38_0.bind(this)));
    var disposable_8:Function = this.renderer.listen(this._el_38,'keyup.space',this.eventHandler(this._handle_keyup_space_38_1.bind(this)));
    this._expr_52 = import7.UNINITIALIZED;
    this._expr_53 = import7.UNINITIALIZED;
    this._expr_54 = import7.UNINITIALIZED;
    this._expr_55 = import7.UNINITIALIZED;
    this._expr_56 = import7.UNINITIALIZED;
    this._expr_57 = import7.UNINITIALIZED;
    this._expr_58 = import7.UNINITIALIZED;
    this._expr_59 = import7.UNINITIALIZED;
    this._expr_60 = import7.UNINITIALIZED;
    this._expr_61 = import7.UNINITIALIZED;
    this._expr_62 = import7.UNINITIALIZED;
    this._expr_63 = import7.UNINITIALIZED;
    this._expr_64 = import7.UNINITIALIZED;
    this._expr_65 = import7.UNINITIALIZED;
    this._expr_66 = import7.UNINITIALIZED;
    this._expr_67 = import7.UNINITIALIZED;
    this._expr_68 = import7.UNINITIALIZED;
    this._expr_69 = import7.UNINITIALIZED;
    this._expr_70 = import7.UNINITIALIZED;
    this._expr_71 = import7.UNINITIALIZED;
    this._expr_72 = import7.UNINITIALIZED;
    this._expr_73 = import7.UNINITIALIZED;
    this._expr_74 = import7.UNINITIALIZED;
    this._expr_75 = import7.UNINITIALIZED;
    this._expr_76 = import7.UNINITIALIZED;
    var disposable_9:Function = this.renderer.listen(this._el_60,'click',this.eventHandler(this._handle_click_60_0.bind(this)));
    this._expr_78 = import7.UNINITIALIZED;
    var disposable_10:Function = this.renderer.listen(this._el_72,'click',this.eventHandler(this._handle_click_72_0.bind(this)));
    this._expr_80 = import7.UNINITIALIZED;
    this._expr_81 = import7.UNINITIALIZED;
    this._expr_82 = import7.UNINITIALIZED;
    this._viewQuery_SignaturePad_0.reset([this._SignaturePad_63_4]);
    this.context.signaturePad = this._viewQuery_SignaturePad_0.first;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._text_56,
      this._el_57,
      this._text_58,
      this._el_59,
      this._el_60,
      this._text_61,
      this._text_62,
      this._el_63,
      this._text_64,
      this._text_65,
      this._text_66,
      this._el_67,
      this._text_68,
      this._el_69,
      this._text_70,
      this._text_71,
      this._el_72,
      this._text_73,
      this._text_74,
      this._text_75,
      this._el_76,
      this._text_77,
      this._el_78,
      this._text_79,
      this._text_80,
      this._text_81
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7,
      disposable_8,
      disposable_9,
      disposable_10
    ]
    ,[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import18.ToolbarTitle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._ToolbarTitle_4_4; }
    if (((token === import17.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Navbar_2_4; }
    if (((token === import16.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Header_0_3; }
    if (((token === import22.FormControlName) && (13 === requestNodeIndex))) { return this._FormControlName_13_4; }
    if (((token === import47.NgControl) && (13 === requestNodeIndex))) { return this._NgControl_13_5; }
    if (((token === import21.NgControlStatus) && (13 === requestNodeIndex))) { return this._NgControlStatus_13_6; }
    if (((token === import23.TextInput) && (13 === requestNodeIndex))) { return this._TextInput_13_7; }
    if (((token === import22.FormControlName) && (15 === requestNodeIndex))) { return this._FormControlName_15_4; }
    if (((token === import47.NgControl) && (15 === requestNodeIndex))) { return this._NgControl_15_5; }
    if (((token === import21.NgControlStatus) && (15 === requestNodeIndex))) { return this._NgControlStatus_15_6; }
    if (((token === import23.TextInput) && (15 === requestNodeIndex))) { return this._TextInput_15_7; }
    if (((token === import25.Label) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._Label_19_3; }
    if (((token === import26.DateTime) && (22 === requestNodeIndex))) { return this._DateTime_22_4; }
    if (((token === import48.NG_VALUE_ACCESSOR) && (22 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_22_5; }
    if (((token === import22.FormControlName) && (22 === requestNodeIndex))) { return this._FormControlName_22_6; }
    if (((token === import47.NgControl) && (22 === requestNodeIndex))) { return this._NgControl_22_7; }
    if (((token === import21.NgControlStatus) && (22 === requestNodeIndex))) { return this._NgControlStatus_22_8; }
    if (((token === import24.Item) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._Item_17_4; }
    if (((token === import24.ItemContent) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._ItemContent_17_5; }
    if (((token === import25.Label) && ((27 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._Label_27_3; }
    if (((token === import26.DateTime) && (30 === requestNodeIndex))) { return this._DateTime_30_4; }
    if (((token === import48.NG_VALUE_ACCESSOR) && (30 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_30_5; }
    if (((token === import22.FormControlName) && (30 === requestNodeIndex))) { return this._FormControlName_30_6; }
    if (((token === import47.NgControl) && (30 === requestNodeIndex))) { return this._NgControl_30_7; }
    if (((token === import21.NgControlStatus) && (30 === requestNodeIndex))) { return this._NgControlStatus_30_8; }
    if (((token === import24.Item) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._Item_25_4; }
    if (((token === import24.ItemContent) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._ItemContent_25_5; }
    if (((token === import25.Label) && ((35 <= requestNodeIndex) && (requestNodeIndex <= 36)))) { return this._Label_35_3; }
    if (((token === import26.DateTime) && (38 === requestNodeIndex))) { return this._DateTime_38_4; }
    if (((token === import48.NG_VALUE_ACCESSOR) && (38 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_38_5; }
    if (((token === import22.FormControlName) && (38 === requestNodeIndex))) { return this._FormControlName_38_6; }
    if (((token === import47.NgControl) && (38 === requestNodeIndex))) { return this._NgControl_38_7; }
    if (((token === import21.NgControlStatus) && (38 === requestNodeIndex))) { return this._NgControlStatus_38_8; }
    if (((token === import24.Item) && ((33 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._Item_33_4; }
    if (((token === import24.ItemContent) && ((33 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._ItemContent_33_5; }
    if (((token === import25.Label) && ((43 <= requestNodeIndex) && (requestNodeIndex <= 44)))) { return this._Label_43_3; }
    if (((token === import22.FormControlName) && (46 === requestNodeIndex))) { return this._FormControlName_46_4; }
    if (((token === import47.NgControl) && (46 === requestNodeIndex))) { return this._NgControl_46_5; }
    if (((token === import21.NgControlStatus) && (46 === requestNodeIndex))) { return this._NgControlStatus_46_6; }
    if (((token === import23.TextArea) && (46 === requestNodeIndex))) { return this._TextArea_46_7; }
    if (((token === import24.Item) && ((41 <= requestNodeIndex) && (requestNodeIndex <= 47)))) { return this._Item_41_4; }
    if (((token === import24.ItemContent) && ((41 <= requestNodeIndex) && (requestNodeIndex <= 47)))) { return this._ItemContent_41_5; }
    if (((token === import25.Label) && ((51 <= requestNodeIndex) && (requestNodeIndex <= 52)))) { return this._Label_51_3; }
    if (((token === import22.FormControlName) && (54 === requestNodeIndex))) { return this._FormControlName_54_4; }
    if (((token === import47.NgControl) && (54 === requestNodeIndex))) { return this._NgControl_54_5; }
    if (((token === import21.NgControlStatus) && (54 === requestNodeIndex))) { return this._NgControlStatus_54_6; }
    if (((token === import23.TextInput) && (54 === requestNodeIndex))) { return this._TextInput_54_7; }
    if (((token === import24.Item) && ((49 <= requestNodeIndex) && (requestNodeIndex <= 55)))) { return this._Item_49_4; }
    if (((token === import24.ItemContent) && ((49 <= requestNodeIndex) && (requestNodeIndex <= 55)))) { return this._ItemContent_49_5; }
    if (((token === import27.Button) && ((60 <= requestNodeIndex) && (requestNodeIndex <= 61)))) { return this._Button_60_4; }
    if (((token === import28.SignaturePad) && (63 === requestNodeIndex))) { return this._SignaturePad_63_4; }
    if (((token === import24.Item) && ((57 <= requestNodeIndex) && (requestNodeIndex <= 65)))) { return this._Item_57_4; }
    if (((token === import24.ItemContent) && ((57 <= requestNodeIndex) && (requestNodeIndex <= 65)))) { return this._ItemContent_57_5; }
    if (((token === import27.Button) && ((69 <= requestNodeIndex) && (requestNodeIndex <= 70)))) { return this._Button_69_4; }
    if (((token === import27.Button) && ((72 <= requestNodeIndex) && (requestNodeIndex <= 73)))) { return this._Button_72_4; }
    if (((token === import24.Item) && ((67 <= requestNodeIndex) && (requestNodeIndex <= 74)))) { return this._Item_67_4; }
    if (((token === import24.ItemContent) && ((67 <= requestNodeIndex) && (requestNodeIndex <= 74)))) { return this._ItemContent_67_5; }
    if (((token === import24.Item) && ((76 <= requestNodeIndex) && (requestNodeIndex <= 79)))) { return this._Item_76_4; }
    if (((token === import24.ItemContent) && ((76 <= requestNodeIndex) && (requestNodeIndex <= 79)))) { return this._ItemContent_76_5; }
    if (((token === import20.FormGroupDirective) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 80)))) { return this._FormGroupDirective_11_3; }
    if (((token === import49.ControlContainer) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 80)))) { return this._ControlContainer_11_4; }
    if (((token === import21.NgControlStatusGroup) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 80)))) { return this._NgControlStatusGroup_11_5; }
    if (((token === import19.Content) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 81)))) { return this._Content_9_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_9_4.ngOnInit(); }
    changes = (null as any);
    const currVal_6:any = this.context.myForm;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._FormGroupDirective_11_3.form = currVal_6;
      if ((changes === (null as any))) { (changes = {}); }
      changes['form'] = new import7.SimpleChange(this._expr_6,currVal_6);
      this._expr_6 = currVal_6;
    }
    if ((changes !== (null as any))) { this._FormGroupDirective_11_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_13:any = 'id';
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this._FormControlName_13_4.name = currVal_13;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_13,currVal_13);
      this._expr_13 = currVal_13;
    }
    if ((changes !== (null as any))) { this._FormControlName_13_4.ngOnChanges(changes); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._TextInput_13_7.ngOnInit(); }
    changes = (null as any);
    const currVal_20:any = 'clienteid';
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this._FormControlName_15_4.name = currVal_20;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_20,currVal_20);
      this._expr_20 = currVal_20;
    }
    if ((changes !== (null as any))) { this._FormControlName_15_4.ngOnChanges(changes); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._TextInput_15_7.ngOnInit(); }
    const currVal_29:any = 'DD/MM/YYYY';
    if (import4.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this._DateTime_22_4.displayFormat = currVal_29;
      this._expr_29 = currVal_29;
    }
    changes = (null as any);
    const currVal_31:any = 'fecha';
    if (import4.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this._FormControlName_22_6.name = currVal_31;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_31,currVal_31);
      this._expr_31 = currVal_31;
    }
    if ((changes !== (null as any))) { this._FormControlName_22_6.ngOnChanges(changes); }
    const currVal_40:any = 'HH:mm';
    if (import4.checkBinding(throwOnChange,this._expr_40,currVal_40)) {
      this._DateTime_30_4.displayFormat = currVal_40;
      this._expr_40 = currVal_40;
    }
    const currVal_41:any = '00,10,20,30,40,50';
    if (import4.checkBinding(throwOnChange,this._expr_41,currVal_41)) {
      this._DateTime_30_4.minuteValues = currVal_41;
      this._expr_41 = currVal_41;
    }
    changes = (null as any);
    const currVal_43:any = 'horaini';
    if (import4.checkBinding(throwOnChange,this._expr_43,currVal_43)) {
      this._FormControlName_30_6.name = currVal_43;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_43,currVal_43);
      this._expr_43 = currVal_43;
    }
    if ((changes !== (null as any))) { this._FormControlName_30_6.ngOnChanges(changes); }
    const currVal_52:any = 'HH:mm';
    if (import4.checkBinding(throwOnChange,this._expr_52,currVal_52)) {
      this._DateTime_38_4.displayFormat = currVal_52;
      this._expr_52 = currVal_52;
    }
    const currVal_53:any = '00,10,20,30,40,50';
    if (import4.checkBinding(throwOnChange,this._expr_53,currVal_53)) {
      this._DateTime_38_4.minuteValues = currVal_53;
      this._expr_53 = currVal_53;
    }
    changes = (null as any);
    const currVal_55:any = 'horafin';
    if (import4.checkBinding(throwOnChange,this._expr_55,currVal_55)) {
      this._FormControlName_38_6.name = currVal_55;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_55,currVal_55);
      this._expr_55 = currVal_55;
    }
    if ((changes !== (null as any))) { this._FormControlName_38_6.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_62:any = 'trabajorealizado';
    if (import4.checkBinding(throwOnChange,this._expr_62,currVal_62)) {
      this._FormControlName_46_4.name = currVal_62;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_62,currVal_62);
      this._expr_62 = currVal_62;
    }
    if ((changes !== (null as any))) { this._FormControlName_46_4.ngOnChanges(changes); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._TextArea_46_7.ngOnInit(); }
    changes = (null as any);
    const currVal_69:any = 'personafirma';
    if (import4.checkBinding(throwOnChange,this._expr_69,currVal_69)) {
      this._FormControlName_54_4.name = currVal_69;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_69,currVal_69);
      this._expr_69 = currVal_69;
    }
    if ((changes !== (null as any))) { this._FormControlName_54_4.ngOnChanges(changes); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._TextInput_54_7.ngOnInit(); }
    const currVal_78:any = this.context.signaturePadOptions;
    if (import4.checkBinding(throwOnChange,this._expr_78,currVal_78)) {
      this._SignaturePad_63_4.options = currVal_78;
      this._expr_78 = currVal_78;
    }
    changed = false;
    const currVal_80:any = 'danger';
    if (import4.checkBinding(throwOnChange,this._expr_80,currVal_80)) {
      this._Button_72_4.color = currVal_80;
      changed = true;
      this._expr_80 = currVal_80;
    }
    if (changed) { this._appEl_72.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_17_1.dirty) {
        this._query_Button_17_1.reset([]);
        this._Item_17_4._buttons = this._query_Button_17_1;
        this._query_Button_17_1.notifyOnChanges();
      }
      if (this._query_Icon_17_2.dirty) {
        this._query_Icon_17_2.reset([]);
        this._Item_17_4._icons = this._query_Icon_17_2;
        this._query_Icon_17_2.notifyOnChanges();
      }
      if (this._query_Button_25_1.dirty) {
        this._query_Button_25_1.reset([]);
        this._Item_25_4._buttons = this._query_Button_25_1;
        this._query_Button_25_1.notifyOnChanges();
      }
      if (this._query_Icon_25_2.dirty) {
        this._query_Icon_25_2.reset([]);
        this._Item_25_4._icons = this._query_Icon_25_2;
        this._query_Icon_25_2.notifyOnChanges();
      }
      if (this._query_Button_33_1.dirty) {
        this._query_Button_33_1.reset([]);
        this._Item_33_4._buttons = this._query_Button_33_1;
        this._query_Button_33_1.notifyOnChanges();
      }
      if (this._query_Icon_33_2.dirty) {
        this._query_Icon_33_2.reset([]);
        this._Item_33_4._icons = this._query_Icon_33_2;
        this._query_Icon_33_2.notifyOnChanges();
      }
      if (this._query_Button_41_1.dirty) {
        this._query_Button_41_1.reset([]);
        this._Item_41_4._buttons = this._query_Button_41_1;
        this._query_Button_41_1.notifyOnChanges();
      }
      if (this._query_Icon_41_2.dirty) {
        this._query_Icon_41_2.reset([]);
        this._Item_41_4._icons = this._query_Icon_41_2;
        this._query_Icon_41_2.notifyOnChanges();
      }
      if (this._query_Button_49_1.dirty) {
        this._query_Button_49_1.reset([]);
        this._Item_49_4._buttons = this._query_Button_49_1;
        this._query_Button_49_1.notifyOnChanges();
      }
      if (this._query_Icon_49_2.dirty) {
        this._query_Icon_49_2.reset([]);
        this._Item_49_4._icons = this._query_Icon_49_2;
        this._query_Icon_49_2.notifyOnChanges();
      }
      if (this._query_Button_57_1.dirty) {
        this._query_Button_57_1.reset([this._Button_60_4]);
        this._Item_57_4._buttons = this._query_Button_57_1;
        this._query_Button_57_1.notifyOnChanges();
      }
      if (this._query_Icon_57_2.dirty) {
        this._query_Icon_57_2.reset([]);
        this._Item_57_4._icons = this._query_Icon_57_2;
        this._query_Icon_57_2.notifyOnChanges();
      }
      if (this._query_Button_67_1.dirty) {
        this._query_Button_67_1.reset([
          this._Button_69_4,
          this._Button_72_4
        ]
        );
        this._Item_67_4._buttons = this._query_Button_67_1;
        this._query_Button_67_1.notifyOnChanges();
      }
      if (this._query_Icon_67_2.dirty) {
        this._query_Icon_67_2.reset([]);
        this._Item_67_4._icons = this._query_Icon_67_2;
        this._query_Icon_67_2.notifyOnChanges();
      }
      if (this._query_Button_76_1.dirty) {
        this._query_Button_76_1.reset([]);
        this._Item_76_4._buttons = this._query_Button_76_1;
        this._query_Button_76_1.notifyOnChanges();
      }
      if (this._query_Icon_76_2.dirty) {
        this._query_Icon_76_2.reset([]);
        this._Item_76_4._icons = this._query_Icon_76_2;
        this._query_Icon_76_2.notifyOnChanges();
      }
      this._TextInput_13_7.ngAfterContentChecked();
      this._TextInput_15_7.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._DateTime_22_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_17_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._DateTime_30_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_25_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._DateTime_38_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_33_4.ngAfterContentInit(); }
      this._TextArea_46_7.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_41_4.ngAfterContentInit(); }
      this._TextInput_54_7.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_49_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_60_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._SignaturePad_63_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_57_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_69_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_72_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_67_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_76_4.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_2_4._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Content_9_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_9,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_7:any = this._NgControlStatusGroup_11_5.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_11,'ng-untouched',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatusGroup_11_5.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_11,'ng-touched',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatusGroup_11_5.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_11,'ng-pristine',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._NgControlStatusGroup_11_5.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_11,'ng-dirty',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this._NgControlStatusGroup_11_5.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_11,'ng-valid',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this._NgControlStatusGroup_11_5.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_11,'ng-invalid',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_14:any = this._NgControlStatus_13_6.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_13,'ng-untouched',currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = this._NgControlStatus_13_6.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_13,'ng-touched',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = this._NgControlStatus_13_6.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_13,'ng-pristine',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = this._NgControlStatus_13_6.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_13,'ng-dirty',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this._NgControlStatus_13_6.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_13,'ng-valid',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this._NgControlStatus_13_6.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_13,'ng-invalid',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_21:any = this._NgControlStatus_15_6.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setElementClass(this._el_15,'ng-untouched',currVal_21);
      this._expr_21 = currVal_21;
    }
    const currVal_22:any = this._NgControlStatus_15_6.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setElementClass(this._el_15,'ng-touched',currVal_22);
      this._expr_22 = currVal_22;
    }
    const currVal_23:any = this._NgControlStatus_15_6.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this.renderer.setElementClass(this._el_15,'ng-pristine',currVal_23);
      this._expr_23 = currVal_23;
    }
    const currVal_24:any = this._NgControlStatus_15_6.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setElementClass(this._el_15,'ng-dirty',currVal_24);
      this._expr_24 = currVal_24;
    }
    const currVal_25:any = this._NgControlStatus_15_6.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setElementClass(this._el_15,'ng-valid',currVal_25);
      this._expr_25 = currVal_25;
    }
    const currVal_26:any = this._NgControlStatus_15_6.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this.renderer.setElementClass(this._el_15,'ng-invalid',currVal_26);
      this._expr_26 = currVal_26;
    }
    const currVal_30:any = this._DateTime_22_4._disabled;
    if (import4.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this.renderer.setElementClass(this._el_22,'datetime-disabled',currVal_30);
      this._expr_30 = currVal_30;
    }
    const currVal_32:any = this._NgControlStatus_22_8.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_32,currVal_32)) {
      this.renderer.setElementClass(this._el_22,'ng-untouched',currVal_32);
      this._expr_32 = currVal_32;
    }
    const currVal_33:any = this._NgControlStatus_22_8.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_33,currVal_33)) {
      this.renderer.setElementClass(this._el_22,'ng-touched',currVal_33);
      this._expr_33 = currVal_33;
    }
    const currVal_34:any = this._NgControlStatus_22_8.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_34,currVal_34)) {
      this.renderer.setElementClass(this._el_22,'ng-pristine',currVal_34);
      this._expr_34 = currVal_34;
    }
    const currVal_35:any = this._NgControlStatus_22_8.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_35,currVal_35)) {
      this.renderer.setElementClass(this._el_22,'ng-dirty',currVal_35);
      this._expr_35 = currVal_35;
    }
    const currVal_36:any = this._NgControlStatus_22_8.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_36,currVal_36)) {
      this.renderer.setElementClass(this._el_22,'ng-valid',currVal_36);
      this._expr_36 = currVal_36;
    }
    const currVal_37:any = this._NgControlStatus_22_8.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_37,currVal_37)) {
      this.renderer.setElementClass(this._el_22,'ng-invalid',currVal_37);
      this._expr_37 = currVal_37;
    }
    const currVal_42:any = this._DateTime_30_4._disabled;
    if (import4.checkBinding(throwOnChange,this._expr_42,currVal_42)) {
      this.renderer.setElementClass(this._el_30,'datetime-disabled',currVal_42);
      this._expr_42 = currVal_42;
    }
    const currVal_44:any = this._NgControlStatus_30_8.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_44,currVal_44)) {
      this.renderer.setElementClass(this._el_30,'ng-untouched',currVal_44);
      this._expr_44 = currVal_44;
    }
    const currVal_45:any = this._NgControlStatus_30_8.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_45,currVal_45)) {
      this.renderer.setElementClass(this._el_30,'ng-touched',currVal_45);
      this._expr_45 = currVal_45;
    }
    const currVal_46:any = this._NgControlStatus_30_8.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_46,currVal_46)) {
      this.renderer.setElementClass(this._el_30,'ng-pristine',currVal_46);
      this._expr_46 = currVal_46;
    }
    const currVal_47:any = this._NgControlStatus_30_8.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_47,currVal_47)) {
      this.renderer.setElementClass(this._el_30,'ng-dirty',currVal_47);
      this._expr_47 = currVal_47;
    }
    const currVal_48:any = this._NgControlStatus_30_8.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_48,currVal_48)) {
      this.renderer.setElementClass(this._el_30,'ng-valid',currVal_48);
      this._expr_48 = currVal_48;
    }
    const currVal_49:any = this._NgControlStatus_30_8.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_49,currVal_49)) {
      this.renderer.setElementClass(this._el_30,'ng-invalid',currVal_49);
      this._expr_49 = currVal_49;
    }
    const currVal_54:any = this._DateTime_38_4._disabled;
    if (import4.checkBinding(throwOnChange,this._expr_54,currVal_54)) {
      this.renderer.setElementClass(this._el_38,'datetime-disabled',currVal_54);
      this._expr_54 = currVal_54;
    }
    const currVal_56:any = this._NgControlStatus_38_8.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_56,currVal_56)) {
      this.renderer.setElementClass(this._el_38,'ng-untouched',currVal_56);
      this._expr_56 = currVal_56;
    }
    const currVal_57:any = this._NgControlStatus_38_8.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_57,currVal_57)) {
      this.renderer.setElementClass(this._el_38,'ng-touched',currVal_57);
      this._expr_57 = currVal_57;
    }
    const currVal_58:any = this._NgControlStatus_38_8.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_58,currVal_58)) {
      this.renderer.setElementClass(this._el_38,'ng-pristine',currVal_58);
      this._expr_58 = currVal_58;
    }
    const currVal_59:any = this._NgControlStatus_38_8.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_59,currVal_59)) {
      this.renderer.setElementClass(this._el_38,'ng-dirty',currVal_59);
      this._expr_59 = currVal_59;
    }
    const currVal_60:any = this._NgControlStatus_38_8.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_60,currVal_60)) {
      this.renderer.setElementClass(this._el_38,'ng-valid',currVal_60);
      this._expr_60 = currVal_60;
    }
    const currVal_61:any = this._NgControlStatus_38_8.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_61,currVal_61)) {
      this.renderer.setElementClass(this._el_38,'ng-invalid',currVal_61);
      this._expr_61 = currVal_61;
    }
    const currVal_63:any = this._NgControlStatus_46_6.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_63,currVal_63)) {
      this.renderer.setElementClass(this._el_46,'ng-untouched',currVal_63);
      this._expr_63 = currVal_63;
    }
    const currVal_64:any = this._NgControlStatus_46_6.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_64,currVal_64)) {
      this.renderer.setElementClass(this._el_46,'ng-touched',currVal_64);
      this._expr_64 = currVal_64;
    }
    const currVal_65:any = this._NgControlStatus_46_6.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_65,currVal_65)) {
      this.renderer.setElementClass(this._el_46,'ng-pristine',currVal_65);
      this._expr_65 = currVal_65;
    }
    const currVal_66:any = this._NgControlStatus_46_6.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_66,currVal_66)) {
      this.renderer.setElementClass(this._el_46,'ng-dirty',currVal_66);
      this._expr_66 = currVal_66;
    }
    const currVal_67:any = this._NgControlStatus_46_6.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_67,currVal_67)) {
      this.renderer.setElementClass(this._el_46,'ng-valid',currVal_67);
      this._expr_67 = currVal_67;
    }
    const currVal_68:any = this._NgControlStatus_46_6.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_68,currVal_68)) {
      this.renderer.setElementClass(this._el_46,'ng-invalid',currVal_68);
      this._expr_68 = currVal_68;
    }
    const currVal_70:any = this._NgControlStatus_54_6.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_70,currVal_70)) {
      this.renderer.setElementClass(this._el_54,'ng-untouched',currVal_70);
      this._expr_70 = currVal_70;
    }
    const currVal_71:any = this._NgControlStatus_54_6.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_71,currVal_71)) {
      this.renderer.setElementClass(this._el_54,'ng-touched',currVal_71);
      this._expr_71 = currVal_71;
    }
    const currVal_72:any = this._NgControlStatus_54_6.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_72,currVal_72)) {
      this.renderer.setElementClass(this._el_54,'ng-pristine',currVal_72);
      this._expr_72 = currVal_72;
    }
    const currVal_73:any = this._NgControlStatus_54_6.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_73,currVal_73)) {
      this.renderer.setElementClass(this._el_54,'ng-dirty',currVal_73);
      this._expr_73 = currVal_73;
    }
    const currVal_74:any = this._NgControlStatus_54_6.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_74,currVal_74)) {
      this.renderer.setElementClass(this._el_54,'ng-valid',currVal_74);
      this._expr_74 = currVal_74;
    }
    const currVal_75:any = this._NgControlStatus_54_6.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_75,currVal_75)) {
      this.renderer.setElementClass(this._el_54,'ng-invalid',currVal_75);
      this._expr_75 = currVal_75;
    }
    const currVal_76:any = ((this.context.firmaImg != (null as any)) && (this.context.firmaImg != ''));
    if (import4.checkBinding(throwOnChange,this._expr_76,currVal_76)) {
      this.renderer.setElementProperty(this._el_57,'hidden',currVal_76);
      this._expr_76 = currVal_76;
    }
    const currVal_81:any = import4.interpolate(1,'',this.context.firmaImg,'');
    if (import4.checkBinding(throwOnChange,this._expr_81,currVal_81)) {
      this.renderer.setElementProperty(this._el_78,'src',this.viewUtils.sanitizer.sanitize(import50.SecurityContext.URL,currVal_81));
      this._expr_81 = currVal_81;
    }
    const currVal_82:any = ((this.context.firmaImg == (null as any)) || (this.context.firmaImg == ''));
    if (import4.checkBinding(throwOnChange,this._expr_82,currVal_82)) {
      this.renderer.setElementProperty(this._el_78,'hidden',currVal_82);
      this._expr_82 = currVal_82;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._FormControlName_13_4.ngOnDestroy();
    this._TextInput_13_7.ngOnDestroy();
    this._FormControlName_15_4.ngOnDestroy();
    this._TextInput_15_7.ngOnDestroy();
    this._DateTime_22_4.ngOnDestroy();
    this._FormControlName_22_6.ngOnDestroy();
    this._DateTime_30_4.ngOnDestroy();
    this._FormControlName_30_6.ngOnDestroy();
    this._DateTime_38_4.ngOnDestroy();
    this._FormControlName_38_6.ngOnDestroy();
    this._FormControlName_46_4.ngOnDestroy();
    this._TextArea_46_7.ngOnDestroy();
    this._FormControlName_54_4.ngOnDestroy();
    this._TextInput_54_7.ngOnDestroy();
    this._Content_9_4.ngOnDestroy();
  }
  private _handle_ngSubmit_11_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onSubmit()) !== false);
    return (true && pd_0);
  }
  private _handle_submit_11_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._FormGroupDirective_11_3.onSubmit()) !== false);
    return (true && pd_0);
  }
  private _handle_reset_11_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._FormGroupDirective_11_3.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_click_22_0($event:any):boolean {
    this._appEl_22.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DateTime_22_4._click($event)) !== false);
    return (true && pd_0);
  }
  private _handle_keyup_space_22_1($event:any):boolean {
    this._appEl_22.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DateTime_22_4._keyup()) !== false);
    return (true && pd_0);
  }
  private _handle_click_30_0($event:any):boolean {
    this._appEl_30.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DateTime_30_4._click($event)) !== false);
    return (true && pd_0);
  }
  private _handle_keyup_space_30_1($event:any):boolean {
    this._appEl_30.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DateTime_30_4._keyup()) !== false);
    return (true && pd_0);
  }
  private _handle_click_38_0($event:any):boolean {
    this._appEl_38.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DateTime_38_4._click($event)) !== false);
    return (true && pd_0);
  }
  private _handle_keyup_space_38_1($event:any):boolean {
    this._appEl_38.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DateTime_38_4._keyup()) !== false);
    return (true && pd_0);
  }
  private _handle_click_60_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.doOnEnd()) !== false);
    return (true && pd_0);
  }
  private _handle_click_72_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.cancelar()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_ParteEditarComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.ParteEditarComponent> {
  if ((renderType_ParteEditarComponent === (null as any))) { (renderType_ParteEditarComponent = viewUtils.createRenderComponentType('/Users/franciscogarcia/Documents/angular2/ionic2partes-rc/.tmp/pages/parte/parte-editar.component.html',0,import13.ViewEncapsulation.None,styles_ParteEditarComponent,{})); }
  return new _View_ParteEditarComponent0(viewUtils,parentInjector,declarationEl);
}