/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../service/cliente.service';
import * as import4 from './cliente-list.component';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/change_detection';
import * as import9 from 'ionic-angular/platform/platform';
import * as import10 from '../../provider/database.provider';
import * as import11 from 'ionic-angular/navigation/nav-controller';
import * as import12 from 'ionic-angular/navigation/nav-params';
import * as import13 from 'ionic-angular/components/action-sheet/action-sheet';
import * as import14 from '../../service/varios.service';
import * as import15 from '@angular/core/src/metadata/view';
import * as import16 from '@angular/core/src/linker/component_factory';
import * as import17 from 'ionic-angular/components/toolbar/toolbar';
import * as import18 from 'ionic-angular/components/navbar/navbar';
import * as import19 from 'ionic-angular/components/button/button';
import * as import20 from 'ionic-angular/components/menu/menu-toggle';
import * as import21 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import22 from '@angular/core/src/linker/query_list';
import * as import23 from 'ionic-angular/components/icon/icon';
import * as import24 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import25 from 'ionic-angular/components/content/content';
import * as import26 from 'ionic-angular/components/list/list';
import * as import27 from 'ionic-angular/components/item/item';
import * as import28 from 'ionic-angular/components/list/list-header';
import * as import29 from '@angular/common/src/directives/ng_for';
import * as import30 from 'ionic-angular/config/config';
import * as import31 from '@angular/core/src/linker/element_ref';
import * as import32 from 'ionic-angular/navigation/view-controller';
import * as import33 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import34 from 'ionic-angular/components/app/app';
import * as import35 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import36 from 'ionic-angular/components/menu/menu-controller';
import * as import37 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import38 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import39 from 'ionic-angular/util/keyboard';
import * as import40 from '@angular/core/src/zone/ng_zone';
import * as import41 from 'ionic-angular/components/tabs/tabs';
import * as import42 from 'ionic-angular/gestures/gesture-controller';
import * as import43 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import44 from 'ionic-angular/util/form';
import * as import45 from '@angular/core/src/linker/template_ref';
import * as import46 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import47 from 'ionic-angular/components/item/item-sliding';
import * as import48 from '../../node_modules/ionic-angular/components/item/item-sliding.ngfactory';
var renderType_ClienteListComponent_Host:import0.RenderComponentType = (null as any);
class _View_ClienteListComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ClienteService_0_4:import3.ClienteService;
  _ClienteListComponent_0_5:import4.ClienteListComponent;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_ClienteListComponent_Host0,renderType_ClienteListComponent_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ClienteListComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ClienteService_0_4 = new import3.ClienteService(this.parentInjector.get(import9.Platform),this.parentInjector.get(import10.DatabaseProvider));
    this._ClienteListComponent_0_5 = new import4.ClienteListComponent(this.parentInjector.get(import11.NavController),this.parentInjector.get(import12.NavParams),this.parentInjector.get(import13.ActionSheetController),this._ClienteService_0_4,this.parentInjector.get(import14.VariosService));
    this._appEl_0.initComponent(this._ClienteListComponent_0_5,[],compView_0);
    compView_0.create(this._ClienteListComponent_0_5,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.ClienteService) && (0 === requestNodeIndex))) { return this._ClienteService_0_4; }
    if (((token === import4.ClienteListComponent) && (0 === requestNodeIndex))) { return this._ClienteListComponent_0_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._ClienteListComponent_0_5.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ClienteListComponent_Host0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_ClienteListComponent_Host === (null as any))) { (renderType_ClienteListComponent_Host = viewUtils.createRenderComponentType('',0,import15.ViewEncapsulation.None,[],{})); }
  return new _View_ClienteListComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const ClienteListComponentNgFactory:import16.ComponentFactory<import4.ClienteListComponent> = new import16.ComponentFactory<import4.ClienteListComponent>('ng-component',viewFactory_ClienteListComponent_Host0,import4.ClienteListComponent);
const styles_ClienteListComponent:any[] = [];
var renderType_ClienteListComponent:import0.RenderComponentType = (null as any);
class _View_ClienteListComponent0 extends import1.AppView<import4.ClienteListComponent> {
  _el_0:any;
  _Header_0_3:import17.Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Navbar_2_4:import18.Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _Button_4_4:import19.Button;
  _MenuToggle_4_5:import20.MenuToggle;
  _ToolbarItem_4_6:import21.ToolbarItem;
  _query_Button_4_0:import22.QueryList<any>;
  _text_5:any;
  _el_6:any;
  _Icon_6_3:import23.Icon;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import2.AppElement;
  _ToolbarTitle_9_4:import24.ToolbarTitle;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  /*private*/ _appEl_14:import2.AppElement;
  _Content_14_4:import25.Content;
  _text_15:any;
  _el_16:any;
  _List_16_3:import26.List;
  _text_17:any;
  _el_18:any;
  /*private*/ _appEl_18:import2.AppElement;
  _Item_18_4:import27.Item;
  _ListHeader_18_5:import28.ListHeader;
  _query_Label_18_0:import22.QueryList<any>;
  _query_Button_18_1:import22.QueryList<any>;
  _query_Icon_18_2:import22.QueryList<any>;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  /*private*/ _appEl_21:import2.AppElement;
  _Item_21_4:import27.Item;
  _ItemContent_21_5:import27.ItemContent;
  _query_Label_21_0:import22.QueryList<any>;
  _query_Button_21_1:import22.QueryList<any>;
  _query_Icon_21_2:import22.QueryList<any>;
  _el_22:any;
  /*private*/ _appEl_22:import2.AppElement;
  _Button_22_4:import19.Button;
  _text_23:any;
  _text_24:any;
  _anchor_25:any;
  /*private*/ _appEl_25:import2.AppElement;
  _TemplateRef_25_5:any;
  _NgFor_25_6:import29.NgFor;
  _text_26:any;
  _text_27:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_ClienteListComponent0,renderType_ClienteListComponent,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import17.Header(this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import32.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import33.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import18.Navbar(this.parentInjector.get(import34.App),this.parentInjector.get(import32.ViewController,(null as any)),this.parentInjector.get(import11.NavController,(null as any)),this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_4,'ion-button','');
    this.renderer.setElementAttribute(this._el_4,'menuToggle','');
    this._appEl_4 = new import2.AppElement(4,2,this,this._el_4);
    var compView_4:any = import35.viewFactory_Button0(this.viewUtils,this.injector(4),this._appEl_4);
    this._Button_4_4 = new import19.Button('','',this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_4),this.renderer);
    this._MenuToggle_4_5 = new import20.MenuToggle(this.parentInjector.get(import36.MenuController),new import31.ElementRef(this._el_4),this.parentInjector.get(import32.ViewController,(null as any)),this._Navbar_2_4);
    this._ToolbarItem_4_6 = new import21.ToolbarItem(this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import17.Toolbar,(null as any)),this._Navbar_2_4);
    this._query_Button_4_0 = new import22.QueryList<any>();
    this._appEl_4.initComponent(this._Button_4_4,[],compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_6,'name','menu');
    this.renderer.setElementAttribute(this._el_6,'role','img');
    this._Icon_6_3 = new import23.Icon(this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_6),this.renderer);
    this._text_7 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_4.create(this._Button_4_4,[[].concat([
        this._text_5,
        this._el_6,
        this._text_7
      ]
    )],(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_9 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_9 = new import2.AppElement(9,2,this,this._el_9);
    var compView_9:any = import37.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(9),this._appEl_9);
    this._ToolbarTitle_9_4 = new import24.ToolbarTitle(this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import17.Toolbar,(null as any)),this._Navbar_2_4);
    this._appEl_9.initComponent(this._ToolbarTitle_9_4,[],compView_9);
    this._text_10 = this.renderer.createText((null as any),'Clientes',(null as any));
    compView_9.create(this._ToolbarTitle_9_4,[[].concat([this._text_10])],(null as any));
    this._text_11 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Navbar_2_4,[
      [].concat([this._el_4]),
      [],
      [],
      [].concat([
        this._text_3,
        this._text_8,
        this._el_9,
        this._text_11
      ]
      )
    ]
    ,(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_13 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_14 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this._appEl_14 = new import2.AppElement(14,(null as any),this,this._el_14);
    var compView_14:any = import38.viewFactory_Content0(this.viewUtils,this.injector(14),this._appEl_14);
    this._Content_14_4 = new import25.Content(this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_14),this.renderer,this.parentInjector.get(import34.App),this.parentInjector.get(import39.Keyboard),this.parentInjector.get(import40.NgZone),this.parentInjector.get(import32.ViewController,(null as any)),this.parentInjector.get(import41.Tabs,(null as any)));
    this._appEl_14.initComponent(this._Content_14_4,[],compView_14);
    this._text_15 = this.renderer.createText((null as any),'\n\n',(null as any));
    this._el_16 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this._List_16_3 = new import26.List(this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_16),this.renderer,this.parentInjector.get(import42.GestureController));
    this._text_17 = this.renderer.createText(this._el_16,'\n  ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_16,'ion-list-header',(null as any));
    this.renderer.setElementAttribute(this._el_18,'class','item');
    this._appEl_18 = new import2.AppElement(18,16,this,this._el_18);
    var compView_18:any = import43.viewFactory_Item0(this.viewUtils,this.injector(18),this._appEl_18);
    this._Item_18_4 = new import27.Item(this.parentInjector.get(import44.Form),this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_18),this.renderer);
    this._ListHeader_18_5 = new import28.ListHeader(this.parentInjector.get(import30.Config),this.renderer,new import31.ElementRef(this._el_18),(null as any));
    this._query_Label_18_0 = new import22.QueryList<any>();
    this._query_Button_18_1 = new import22.QueryList<any>();
    this._query_Icon_18_2 = new import22.QueryList<any>();
    this._appEl_18.initComponent(this._Item_18_4,[],compView_18);
    this._text_19 = this.renderer.createText((null as any),'Lista de Clientes',(null as any));
    this._query_Label_18_0.reset([]);
    this._Item_18_4.contentLabel = this._query_Label_18_0.first;
    compView_18.create(this._Item_18_4,[
      [],
      [],
      [].concat([this._text_19]),
      [],
      []
    ]
    ,(null as any));
    this._text_20 = this.renderer.createText(this._el_16,'\n  ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_16,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_21,'class','item item-block');
    this._appEl_21 = new import2.AppElement(21,16,this,this._el_21);
    var compView_21:any = import43.viewFactory_Item0(this.viewUtils,this.injector(21),this._appEl_21);
    this._Item_21_4 = new import27.Item(this.parentInjector.get(import44.Form),this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_21),this.renderer);
    this._ItemContent_21_5 = new import27.ItemContent();
    this._query_Label_21_0 = new import22.QueryList<any>();
    this._query_Button_21_1 = new import22.QueryList<any>();
    this._query_Icon_21_2 = new import22.QueryList<any>();
    this._appEl_21.initComponent(this._Item_21_4,[],compView_21);
    this._el_22 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_22,'full','');
    this.renderer.setElementAttribute(this._el_22,'ion-button','');
    this._appEl_22 = new import2.AppElement(22,21,this,this._el_22);
    var compView_22:any = import35.viewFactory_Button0(this.viewUtils,this.injector(22),this._appEl_22);
    this._Button_22_4 = new import19.Button((null as any),'',this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_22),this.renderer);
    this._appEl_22.initComponent(this._Button_22_4,[],compView_22);
    this._text_23 = this.renderer.createText((null as any),'Añadir cliente',(null as any));
    compView_22.create(this._Button_22_4,[[].concat([this._text_23])],(null as any));
    this._query_Label_21_0.reset([]);
    this._Item_21_4.contentLabel = this._query_Label_21_0.first;
    compView_21.create(this._Item_21_4,[
      [],
      [],
      [].concat([this._el_22]),
      [],
      []
    ]
    ,(null as any));
    this._text_24 = this.renderer.createText(this._el_16,'\n  ',(null as any));
    this._anchor_25 = this.renderer.createTemplateAnchor(this._el_16,(null as any));
    this._appEl_25 = new import2.AppElement(25,16,this,this._anchor_25);
    this._TemplateRef_25_5 = new import45.TemplateRef_(this._appEl_25,viewFactory_ClienteListComponent1);
    this._NgFor_25_6 = new import29.NgFor(this._appEl_25.vcRef,this._TemplateRef_25_5,this.parentInjector.get(import46.IterableDiffers),this.ref);
    this._text_26 = this.renderer.createText(this._el_16,'\n',(null as any));
    this._text_27 = this.renderer.createText((null as any),'\n\n',(null as any));
    compView_14.create(this._Content_14_4,[
      [],
      [].concat([
        this._text_15,
        this._el_16,
        this._text_27
      ]
      ),
      []
    ]
    ,(null as any));
    this._expr_0 = import8.UNINITIALIZED;
    this._expr_1 = import8.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_4,'click',this.eventHandler(this._handle_click_4_0.bind(this)));
    this._expr_3 = import8.UNINITIALIZED;
    this._expr_4 = import8.UNINITIALIZED;
    this._expr_5 = import8.UNINITIALIZED;
    this._expr_6 = import8.UNINITIALIZED;
    this._expr_7 = import8.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_22,'click',this.eventHandler(this._handle_click_22_0.bind(this)));
    this._expr_9 = import8.UNINITIALIZED;
    this._expr_10 = import8.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._anchor_25,
      this._text_26,
      this._text_27
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import23.Icon) && (6 === requestNodeIndex))) { return this._Icon_6_3; }
    if (((token === import19.Button) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Button_4_4; }
    if (((token === import20.MenuToggle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._MenuToggle_4_5; }
    if (((token === import21.ToolbarItem) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._ToolbarItem_4_6; }
    if (((token === import24.ToolbarTitle) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._ToolbarTitle_9_4; }
    if (((token === import18.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._Navbar_2_4; }
    if (((token === import17.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._Header_0_3; }
    if (((token === import27.Item) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._Item_18_4; }
    if (((token === import28.ListHeader) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._ListHeader_18_5; }
    if (((token === import19.Button) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._Button_22_4; }
    if (((token === import27.Item) && ((21 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._Item_21_4; }
    if (((token === import27.ItemContent) && ((21 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._ItemContent_21_5; }
    if (((token === import45.TemplateRef) && (25 === requestNodeIndex))) { return this._TemplateRef_25_5; }
    if (((token === import29.NgFor) && (25 === requestNodeIndex))) { return this._NgFor_25_6; }
    if (((token === import26.List) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._List_16_3; }
    if (((token === import25.Content) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._Content_14_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    var changes:{[key: string]:import8.SimpleChange} = (null as any);
    const currVal_3:any = '';
    if (import5.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._MenuToggle_4_5.menuToggle = currVal_3;
      this._expr_3 = currVal_3;
    }
    const currVal_5:any = 'menu';
    if (import5.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._Icon_6_3.name = currVal_5;
      this._expr_5 = currVal_5;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_14_4.ngOnInit(); }
    changed = false;
    const currVal_9:any = '';
    if (import5.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this._Button_22_4.full = currVal_9;
      changed = true;
      this._expr_9 = currVal_9;
    }
    if (changed) { this._appEl_22.componentView.markAsCheckOnce(); }
    changes = (null as any);
    const currVal_10:any = this.context.clientes;
    if (import5.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._NgFor_25_6.ngForOf = currVal_10;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import8.SimpleChange(this._expr_10,currVal_10);
      this._expr_10 = currVal_10;
    }
    if ((changes !== (null as any))) { this._NgFor_25_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_25_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_4_0.dirty) {
        this._query_Button_4_0.reset([this._Button_4_4]);
        this._ToolbarItem_4_6._buttons = this._query_Button_4_0;
        this._query_Button_4_0.notifyOnChanges();
      }
      if (this._query_Button_18_1.dirty) {
        this._query_Button_18_1.reset([]);
        this._Item_18_4._buttons = this._query_Button_18_1;
        this._query_Button_18_1.notifyOnChanges();
      }
      if (this._query_Icon_18_2.dirty) {
        this._query_Icon_18_2.reset([]);
        this._Item_18_4._icons = this._query_Icon_18_2;
        this._query_Icon_18_2.notifyOnChanges();
      }
      if (this._query_Button_21_1.dirty) {
        this._query_Button_21_1.reset([this._Button_22_4]);
        this._Item_21_4._buttons = this._query_Button_21_1;
        this._query_Button_21_1.notifyOnChanges();
      }
      if (this._query_Icon_21_2.dirty) {
        this._query_Icon_21_2.reset([]);
        this._Item_21_4._icons = this._query_Icon_21_2;
        this._query_Icon_21_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_4_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_18_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_22_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_21_4.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_2_4._hidden;
    if (import5.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4._sbPadding;
    if (import5.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_4:any = this._MenuToggle_4_5.isHidden;
    if (import5.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_4,'hidden',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_6:any = this._Icon_6_3._hidden;
    if (import5.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_6,'hide',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._Content_14_4._sbPadding;
    if (import5.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_14,'statusbar-padding',currVal_7);
      this._expr_7 = currVal_7;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_6_3.ngOnDestroy();
    this._Content_14_4.ngOnDestroy();
  }
  private _handle_click_4_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MenuToggle_4_5.toggle()) !== false);
    return (true && pd_0);
  }
  private _handle_click_22_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.crearCliente()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_ClienteListComponent0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<import4.ClienteListComponent> {
  if ((renderType_ClienteListComponent === (null as any))) { (renderType_ClienteListComponent = viewUtils.createRenderComponentType('/Users/franciscogarcia/Documents/angular2/ionic2partes-rc/.tmp/pages/clientes/cliente-list.html',0,import15.ViewEncapsulation.None,styles_ClienteListComponent,{})); }
  return new _View_ClienteListComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_ClienteListComponent1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ItemSliding_0_4:import47.ItemSliding;
  _query_Item_0_0:import22.QueryList<any>;
  _query_ItemOptions_0_1:import22.QueryList<any>;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Item_2_4:import27.Item;
  _ItemContent_2_5:import27.ItemContent;
  _query_Label_2_0:import22.QueryList<any>;
  _query_Button_2_1:import22.QueryList<any>;
  _query_Icon_2_2:import22.QueryList<any>;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _ItemOptions_8_3:import47.ItemOptions;
  _text_9:any;
  _el_10:any;
  /*private*/ _appEl_10:import2.AppElement;
  _Button_10_4:import19.Button;
  _text_11:any;
  _el_12:any;
  _Icon_12_3:import23.Icon;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  /*private*/ _appEl_15:import2.AppElement;
  _Button_15_4:import19.Button;
  _text_16:any;
  _el_17:any;
  _Icon_17_3:import23.Icon;
  _text_18:any;
  _text_19:any;
  _text_20:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_ClienteListComponent1,renderType_ClienteListComponent,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-item-sliding',(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import48.viewFactory_ItemSliding0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ItemSliding_0_4 = new import47.ItemSliding((<_View_ClienteListComponent0>this.parent)._List_16_3,this.renderer,new import31.ElementRef(this._el_0),this.parent.parentInjector.get(import40.NgZone));
    this._query_Item_0_0 = new import22.QueryList<any>();
    this._query_ItemOptions_0_1 = new import22.QueryList<any>();
    this._appEl_0.initComponent(this._ItemSliding_0_4,[],compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','item item-block');
    this.renderer.setElementAttribute(this._el_2,'ion-item','');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import43.viewFactory_Item0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Item_2_4 = new import27.Item(this.parent.parentInjector.get(import44.Form),this.parent.parentInjector.get(import30.Config),new import31.ElementRef(this._el_2),this.renderer);
    this._ItemContent_2_5 = new import27.ItemContent();
    this._query_Label_2_0 = new import22.QueryList<any>();
    this._query_Button_2_1 = new import22.QueryList<any>();
    this._query_Icon_2_2 = new import22.QueryList<any>();
    this._appEl_2.initComponent(this._Item_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'h2',(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'',(null as any));
    this._text_6 = this.renderer.createText((null as any),' \n    ',(null as any));
    this._query_Label_2_0.reset([]);
    this._Item_2_4.contentLabel = this._query_Label_2_0.first;
    compView_2.create(this._Item_2_4,[
      [],
      [],
      [].concat([
        this._text_3,
        this._el_4,
        this._text_6
      ]
      ),
      [],
      []
    ]
    ,(null as any));
    this._text_7 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_8 = this.renderer.createElement((null as any),'ion-item-options',(null as any));
    this._ItemOptions_8_3 = new import47.ItemOptions(new import31.ElementRef(this._el_8),this.renderer);
    this._text_9 = this.renderer.createText(this._el_8,'\n        ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_8,'button',(null as any));
    this.renderer.setElementAttribute(this._el_10,'color','danger');
    this.renderer.setElementAttribute(this._el_10,'ion-button','');
    this._appEl_10 = new import2.AppElement(10,8,this,this._el_10);
    var compView_10:any = import35.viewFactory_Button0(this.viewUtils,this.injector(10),this._appEl_10);
    this._Button_10_4 = new import19.Button((null as any),'',this.parent.parentInjector.get(import30.Config),new import31.ElementRef(this._el_10),this.renderer);
    this._appEl_10.initComponent(this._Button_10_4,[],compView_10);
    this._text_11 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._el_12 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_12,'name','trash');
    this.renderer.setElementAttribute(this._el_12,'role','img');
    this._Icon_12_3 = new import23.Icon(this.parent.parentInjector.get(import30.Config),new import31.ElementRef(this._el_12),this.renderer);
    this._text_13 = this.renderer.createText((null as any),'\n            Eliminar\n        ',(null as any));
      compView_10.create(this._Button_10_4,[[].concat([
        this._text_11,
        this._el_12,
        this._text_13
      ]
    )],(null as any));
    this._text_14 = this.renderer.createText(this._el_8,'\n        ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_8,'button',(null as any));
    this.renderer.setElementAttribute(this._el_15,'ion-button','');
    this.renderer.setElementAttribute(this._el_15,'light','');
    this._appEl_15 = new import2.AppElement(15,8,this,this._el_15);
    var compView_15:any = import35.viewFactory_Button0(this.viewUtils,this.injector(15),this._appEl_15);
    this._Button_15_4 = new import19.Button((null as any),'',this.parent.parentInjector.get(import30.Config),new import31.ElementRef(this._el_15),this.renderer);
    this._appEl_15.initComponent(this._Button_15_4,[],compView_15);
    this._text_16 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._el_17 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_17,'name','arrow-dropright');
    this.renderer.setElementAttribute(this._el_17,'role','img');
    this._Icon_17_3 = new import23.Icon(this.parent.parentInjector.get(import30.Config),new import31.ElementRef(this._el_17),this.renderer);
    this._text_18 = this.renderer.createText((null as any),'\n            Editar\n        ',(null as any));
      compView_15.create(this._Button_15_4,[[].concat([
        this._text_16,
        this._el_17,
        this._text_18
      ]
    )],(null as any));
    this._text_19 = this.renderer.createText(this._el_8,'\n      ',(null as any));
    this._text_20 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._query_Item_0_0.reset([this._Item_2_4]);
    this._ItemSliding_0_4.item = this._query_Item_0_0.first;
    compView_0.create(this._ItemSliding_0_4,[
      [].concat([this._el_2]),
      [].concat([this._el_8])
    ]
    ,(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_0.bind(this)));
    this._expr_1 = import8.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_10,'click',this.eventHandler(this._handle_click_10_0.bind(this)));
    this._expr_3 = import8.UNINITIALIZED;
    this._expr_4 = import8.UNINITIALIZED;
    this._expr_5 = import8.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_15,'click',this.eventHandler(this._handle_click_15_0.bind(this)));
    this._expr_7 = import8.UNINITIALIZED;
    this._expr_8 = import8.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._text_20
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import27.Item) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Item_2_4; }
    if (((token === import27.ItemContent) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._ItemContent_2_5; }
    if (((token === import23.Icon) && (12 === requestNodeIndex))) { return this._Icon_12_3; }
    if (((token === import19.Button) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._Button_10_4; }
    if (((token === import23.Icon) && (17 === requestNodeIndex))) { return this._Icon_17_3; }
    if (((token === import19.Button) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._Button_15_4; }
    if (((token === import47.ItemOptions) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._ItemOptions_8_3; }
    if (((token === import47.ItemSliding) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._ItemSliding_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    changed = false;
    const currVal_3:any = 'danger';
    if (import5.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._Button_10_4.color = currVal_3;
      changed = true;
      this._expr_3 = currVal_3;
    }
    if (changed) { this._appEl_10.componentView.markAsCheckOnce(); }
    const currVal_4:any = 'trash';
    if (import5.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._Icon_12_3.name = currVal_4;
      this._expr_4 = currVal_4;
    }
    const currVal_7:any = 'arrow-dropright';
    if (import5.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._Icon_17_3.name = currVal_7;
      this._expr_7 = currVal_7;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_2_1.dirty) {
        this._query_Button_2_1.reset([]);
        this._Item_2_4._buttons = this._query_Button_2_1;
        this._query_Button_2_1.notifyOnChanges();
      }
      if (this._query_Icon_2_2.dirty) {
        this._query_Icon_2_2.reset([]);
        this._Item_2_4._icons = this._query_Icon_2_2;
        this._query_Icon_2_2.notifyOnChanges();
      }
      if (this._query_ItemOptions_0_1.dirty) {
        this._query_ItemOptions_0_1.reset([this._ItemOptions_8_3]);
        this._ItemSliding_0_4._itemOptions = this._query_ItemOptions_0_1;
        this._query_ItemOptions_0_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_2_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_10_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_15_4.ngAfterContentInit(); }
    }
    const currVal_1:any = import5.interpolate(2,'',this.context.$implicit.id,' - ',this.context.$implicit.nombre,'');
    if (import5.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_5,currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_5:any = this._Icon_12_3._hidden;
    if (import5.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_12,'hide',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_8:any = this._Icon_17_3._hidden;
    if (import5.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_17,'hide',currVal_8);
      this._expr_8 = currVal_8;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_12_3.ngOnDestroy();
    this._Icon_17_3.ngOnDestroy();
  }
  private _handle_click_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.crearParte(this.context.$implicit.id)) !== false);
    return (true && pd_0);
  }
  private _handle_click_10_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.borrarCliente(this.context.$implicit.id)) !== false);
    return (true && pd_0);
  }
  private _handle_click_15_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.cargaCliente(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ClienteListComponent1(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ClienteListComponent1(viewUtils,parentInjector,declarationEl);
}