/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../service/cliente.service';
import * as import4 from './cliente-editar.component';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/change_detection';
import * as import9 from 'ionic-angular/platform/platform';
import * as import10 from '../../provider/database.provider';
import * as import11 from 'ionic-angular/navigation/nav-controller';
import * as import12 from 'ionic-angular/navigation/nav-params';
import * as import13 from '@angular/forms/src/form_builder';
import * as import14 from '../../service/varios.service';
import * as import15 from '@angular/core/src/metadata/view';
import * as import16 from '@angular/core/src/linker/component_factory';
import * as import17 from 'ionic-angular/components/toolbar/toolbar';
import * as import18 from 'ionic-angular/components/navbar/navbar';
import * as import19 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import20 from 'ionic-angular/components/content/content';
import * as import21 from '@angular/forms/src/directives/reactive_directives/form_group_directive';
import * as import22 from '@angular/forms/src/directives/ng_control_status';
import * as import23 from '@angular/forms/src/directives/reactive_directives/form_control_name';
import * as import24 from 'ionic-angular/components/input/input';
import * as import25 from 'ionic-angular/components/item/item';
import * as import26 from '@angular/core/src/linker/query_list';
import * as import27 from 'ionic-angular/components/label/label';
import * as import28 from 'ionic-angular/components/button/button';
import * as import29 from 'ionic-angular/config/config';
import * as import30 from '@angular/core/src/linker/element_ref';
import * as import31 from 'ionic-angular/navigation/view-controller';
import * as import32 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import33 from 'ionic-angular/components/app/app';
import * as import34 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import35 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import36 from 'ionic-angular/util/keyboard';
import * as import37 from '@angular/core/src/zone/ng_zone';
import * as import38 from 'ionic-angular/components/tabs/tabs';
import * as import39 from '../../node_modules/ionic-angular/components/input/input.ngfactory';
import * as import40 from 'ionic-angular/util/form';
import * as import41 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import42 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import43 from '@angular/forms/src/directives/ng_control';
import * as import44 from '@angular/forms/src/directives/control_container';
var renderType_ClienteEditarComponent_Host:import0.RenderComponentType = (null as any);
class _View_ClienteEditarComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ClienteService_0_4:import3.ClienteService;
  _ClienteEditarComponent_0_5:import4.ClienteEditarComponent;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_ClienteEditarComponent_Host0,renderType_ClienteEditarComponent_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ClienteEditarComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ClienteService_0_4 = new import3.ClienteService(this.parentInjector.get(import9.Platform),this.parentInjector.get(import10.DatabaseProvider));
    this._ClienteEditarComponent_0_5 = new import4.ClienteEditarComponent(this.parentInjector.get(import11.NavController),this.parentInjector.get(import12.NavParams),this.parentInjector.get(import13.FormBuilder),this._ClienteService_0_4,this.parentInjector.get(import14.VariosService));
    this._appEl_0.initComponent(this._ClienteEditarComponent_0_5,([] as any[]),compView_0);
    compView_0.create(this._ClienteEditarComponent_0_5,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.ClienteService) && (0 === requestNodeIndex))) { return this._ClienteService_0_4; }
    if (((token === import4.ClienteEditarComponent) && (0 === requestNodeIndex))) { return this._ClienteEditarComponent_0_5; }
    return notFoundResult;
  }
}
function viewFactory_ClienteEditarComponent_Host0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_ClienteEditarComponent_Host === (null as any))) { (renderType_ClienteEditarComponent_Host = viewUtils.createRenderComponentType('',0,import15.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_ClienteEditarComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const ClienteEditarComponentNgFactory:import16.ComponentFactory<import4.ClienteEditarComponent> = new import16.ComponentFactory<import4.ClienteEditarComponent>('ng-component',viewFactory_ClienteEditarComponent_Host0,import4.ClienteEditarComponent);
const styles_ClienteEditarComponent:any[] = ([] as any[]);
var renderType_ClienteEditarComponent:import0.RenderComponentType = (null as any);
class _View_ClienteEditarComponent0 extends import1.AppView<import4.ClienteEditarComponent> {
  _el_0:any;
  _Header_0_3:import17.Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Navbar_2_4:import18.Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _ToolbarTitle_4_4:import19.ToolbarTitle;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import2.AppElement;
  _Content_9_4:import20.Content;
  _text_10:any;
  _el_11:any;
  _FormGroupDirective_11_3:import21.FormGroupDirective;
  _ControlContainer_11_4:any;
  _NgControlStatusGroup_11_5:import22.NgControlStatusGroup;
  _text_12:any;
  _el_13:any;
  /*private*/ _appEl_13:import2.AppElement;
  _FormControlName_13_4:import23.FormControlName;
  _NgControl_13_5:any;
  _NgControlStatus_13_6:import22.NgControlStatus;
  _TextInput_13_7:import24.TextInput;
  _text_14:any;
  _el_15:any;
  /*private*/ _appEl_15:import2.AppElement;
  _Item_15_4:import25.Item;
  _ItemContent_15_5:import25.ItemContent;
  _query_Label_15_0:import26.QueryList<any>;
  _query_Button_15_1:import26.QueryList<any>;
  _query_Icon_15_2:import26.QueryList<any>;
  _text_16:any;
  _el_17:any;
  _Label_17_3:import27.Label;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  /*private*/ _appEl_20:import2.AppElement;
  _FormControlName_20_4:import23.FormControlName;
  _NgControl_20_5:any;
  _NgControlStatus_20_6:import22.NgControlStatus;
  _TextInput_20_7:import24.TextInput;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  /*private*/ _appEl_23:import2.AppElement;
  _Item_23_4:import25.Item;
  _ItemContent_23_5:import25.ItemContent;
  _query_Label_23_0:import26.QueryList<any>;
  _query_Button_23_1:import26.QueryList<any>;
  _query_Icon_23_2:import26.QueryList<any>;
  _text_24:any;
  _el_25:any;
  _Label_25_3:import27.Label;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  /*private*/ _appEl_28:import2.AppElement;
  _FormControlName_28_4:import23.FormControlName;
  _NgControl_28_5:any;
  _NgControlStatus_28_6:import22.NgControlStatus;
  _TextInput_28_7:import24.TextInput;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  /*private*/ _appEl_31:import2.AppElement;
  _Button_31_4:import28.Button;
  _text_32:any;
  _text_33:any;
  _el_34:any;
  /*private*/ _appEl_34:import2.AppElement;
  _Button_34_4:import28.Button;
  _text_35:any;
  _text_36:any;
  _text_37:any;
  _text_38:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_31:any;
  /*private*/ _expr_32:any;
  /*private*/ _expr_33:any;
  /*private*/ _expr_35:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_ClienteEditarComponent0,renderType_ClienteEditarComponent,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import17.Header(this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import31.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import32.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import18.Navbar(this.parentInjector.get(import33.App),this.parentInjector.get(import31.ViewController,(null as any)),this.parentInjector.get(import11.NavController,(null as any)),this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_4 = new import2.AppElement(4,2,this,this._el_4);
    var compView_4:any = import34.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ToolbarTitle_4_4 = new import19.ToolbarTitle(this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import17.Toolbar,(null as any)),this._Navbar_2_4);
    this._appEl_4.initComponent(this._ToolbarTitle_4_4,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'Crear cliente',(null as any));
    compView_4.create(this._ToolbarTitle_4_4,[([] as any[]).concat([this._text_5])],(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n    ',(null as any));
    compView_2.create(this._Navbar_2_4,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._el_4,
        this._text_6
      ]
      )
    ]
    ,(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_8 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_9 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this._appEl_9 = new import2.AppElement(9,(null as any),this,this._el_9);
    var compView_9:any = import35.viewFactory_Content0(this.viewUtils,this.injector(9),this._appEl_9);
    this._Content_9_4 = new import20.Content(this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import33.App),this.parentInjector.get(import36.Keyboard),this.parentInjector.get(import37.NgZone),this.parentInjector.get(import31.ViewController,(null as any)),this.parentInjector.get(import38.Tabs,(null as any)));
    this._appEl_9.initComponent(this._Content_9_4,([] as any[]),compView_9);
    this._text_10 = this.renderer.createText((null as any),'\n\n    ',(null as any));
    this._el_11 = this.renderer.createElement((null as any),'form',(null as any));
    this._FormGroupDirective_11_3 = new import21.FormGroupDirective((null as any),(null as any));
    this._ControlContainer_11_4 = this._FormGroupDirective_11_3;
    this._NgControlStatusGroup_11_5 = new import22.NgControlStatusGroup(this._ControlContainer_11_4);
    this._text_12 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_11,'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_13,'formControlName','id');
    this.renderer.setElementAttribute(this._el_13,'hidden','');
    this._appEl_13 = new import2.AppElement(13,11,this,this._el_13);
    var compView_13:any = import39.viewFactory_TextInput0(this.viewUtils,this.injector(13),this._appEl_13);
    this._FormControlName_13_4 = new import23.FormControlName(this._ControlContainer_11_4,(null as any),(null as any),(null as any));
    this._NgControl_13_5 = this._FormControlName_13_4;
    this._NgControlStatus_13_6 = new import22.NgControlStatus(this._NgControl_13_5);
    this._TextInput_13_7 = new import24.TextInput(this.parentInjector.get(import29.Config),this.parentInjector.get(import40.Form),this.parentInjector.get(import25.Item,(null as any)),this.parentInjector.get(import33.App),this.parentInjector.get(import9.Platform),new import30.ElementRef(this._el_13),this.renderer,this._Content_9_4,this.parentInjector.get(import11.NavController,(null as any)),this._NgControl_13_5);
    this._appEl_13.initComponent(this._TextInput_13_7,([] as any[]),compView_13);
    compView_13.create(this._TextInput_13_7,([] as any[]),(null as any));
    this._text_14 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_11,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_15,'class','item item-block');
    this._appEl_15 = new import2.AppElement(15,11,this,this._el_15);
    var compView_15:any = import41.viewFactory_Item0(this.viewUtils,this.injector(15),this._appEl_15);
    this._Item_15_4 = new import25.Item(this.parentInjector.get(import40.Form),this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_15),this.renderer);
    this._ItemContent_15_5 = new import25.ItemContent();
    this._query_Label_15_0 = new import26.QueryList<any>();
    this._query_Button_15_1 = new import26.QueryList<any>();
    this._query_Icon_15_2 = new import26.QueryList<any>();
    this._appEl_15.initComponent(this._Item_15_4,([] as any[]),compView_15);
    this._text_16 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_17 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_17,'floating','');
    this._Label_17_3 = new import27.Label(this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_17),this.renderer,'',(null as any),(null as any),(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'Nombre',(null as any));
    this._text_19 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_20 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_20,'formControlName','nombre');
    this._appEl_20 = new import2.AppElement(20,15,this,this._el_20);
    var compView_20:any = import39.viewFactory_TextInput0(this.viewUtils,this.injector(20),this._appEl_20);
    this._FormControlName_20_4 = new import23.FormControlName(this._ControlContainer_11_4,(null as any),(null as any),(null as any));
    this._NgControl_20_5 = this._FormControlName_20_4;
    this._NgControlStatus_20_6 = new import22.NgControlStatus(this._NgControl_20_5);
    this._TextInput_20_7 = new import24.TextInput(this.parentInjector.get(import29.Config),this.parentInjector.get(import40.Form),this._Item_15_4,this.parentInjector.get(import33.App),this.parentInjector.get(import9.Platform),new import30.ElementRef(this._el_20),this.renderer,this._Content_9_4,this.parentInjector.get(import11.NavController,(null as any)),this._NgControl_20_5);
    this._appEl_20.initComponent(this._TextInput_20_7,([] as any[]),compView_20);
    compView_20.create(this._TextInput_20_7,([] as any[]),(null as any));
    this._text_21 = this.renderer.createText((null as any),'\n            \n        ',(null as any));
    this._query_Label_15_0.reset([this._Label_17_3]);
    this._Item_15_4.contentLabel = this._query_Label_15_0.first;
    compView_15.create(this._Item_15_4,[
      ([] as any[]),
      ([] as any[]).concat([this._el_17]),
      ([] as any[]).concat([
        this._text_16,
        this._text_19,
        this._text_21
      ]
      ),
      ([] as any[]).concat([this._el_20]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_22 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_11,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_23,'class','item item-block');
    this._appEl_23 = new import2.AppElement(23,11,this,this._el_23);
    var compView_23:any = import41.viewFactory_Item0(this.viewUtils,this.injector(23),this._appEl_23);
    this._Item_23_4 = new import25.Item(this.parentInjector.get(import40.Form),this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_23),this.renderer);
    this._ItemContent_23_5 = new import25.ItemContent();
    this._query_Label_23_0 = new import26.QueryList<any>();
    this._query_Button_23_1 = new import26.QueryList<any>();
    this._query_Icon_23_2 = new import26.QueryList<any>();
    this._appEl_23.initComponent(this._Item_23_4,([] as any[]),compView_23);
    this._text_24 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_25 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_25,'floating','');
    this._Label_25_3 = new import27.Label(this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_25),this.renderer,'',(null as any),(null as any),(null as any));
    this._text_26 = this.renderer.createText(this._el_25,'Telefono',(null as any));
    this._text_27 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_28 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_28,'formControlName','telefono');
    this._appEl_28 = new import2.AppElement(28,23,this,this._el_28);
    var compView_28:any = import39.viewFactory_TextInput0(this.viewUtils,this.injector(28),this._appEl_28);
    this._FormControlName_28_4 = new import23.FormControlName(this._ControlContainer_11_4,(null as any),(null as any),(null as any));
    this._NgControl_28_5 = this._FormControlName_28_4;
    this._NgControlStatus_28_6 = new import22.NgControlStatus(this._NgControl_28_5);
    this._TextInput_28_7 = new import24.TextInput(this.parentInjector.get(import29.Config),this.parentInjector.get(import40.Form),this._Item_23_4,this.parentInjector.get(import33.App),this.parentInjector.get(import9.Platform),new import30.ElementRef(this._el_28),this.renderer,this._Content_9_4,this.parentInjector.get(import11.NavController,(null as any)),this._NgControl_28_5);
    this._appEl_28.initComponent(this._TextInput_28_7,([] as any[]),compView_28);
    compView_28.create(this._TextInput_28_7,([] as any[]),(null as any));
    this._text_29 = this.renderer.createText((null as any),'\n            \n        ',(null as any));
    this._query_Label_23_0.reset([this._Label_25_3]);
    this._Item_23_4.contentLabel = this._query_Label_23_0.first;
    compView_23.create(this._Item_23_4,[
      ([] as any[]),
      ([] as any[]).concat([this._el_25]),
      ([] as any[]).concat([
        this._text_24,
        this._text_27,
        this._text_29
      ]
      ),
      ([] as any[]).concat([this._el_28]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_30 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._el_31 = this.renderer.createElement(this._el_11,'button',(null as any));
    this.renderer.setElementAttribute(this._el_31,'ion-button','');
    this.renderer.setElementAttribute(this._el_31,'type','submit');
    this._appEl_31 = new import2.AppElement(31,11,this,this._el_31);
    var compView_31:any = import42.viewFactory_Button0(this.viewUtils,this.injector(31),this._appEl_31);
    this._Button_31_4 = new import28.Button((null as any),'',this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_31),this.renderer);
    this._appEl_31.initComponent(this._Button_31_4,([] as any[]),compView_31);
    this._text_32 = this.renderer.createText((null as any),'Enviar',(null as any));
    compView_31.create(this._Button_31_4,[([] as any[]).concat([this._text_32])],(null as any));
    this._text_33 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._el_34 = this.renderer.createElement(this._el_11,'input',(null as any));
    this.renderer.setElementAttribute(this._el_34,'color','danger');
    this.renderer.setElementAttribute(this._el_34,'ion-button','');
    this.renderer.setElementAttribute(this._el_34,'type','button');
    this.renderer.setElementAttribute(this._el_34,'value','Cancelar');
    this._appEl_34 = new import2.AppElement(34,11,this,this._el_34);
    var compView_34:any = import42.viewFactory_Button0(this.viewUtils,this.injector(34),this._appEl_34);
    this._Button_34_4 = new import28.Button((null as any),'',this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_34),this.renderer);
    this._appEl_34.initComponent(this._Button_34_4,([] as any[]),compView_34);
    compView_34.create(this._Button_34_4,[([] as any[])],(null as any));
    this._text_35 = this.renderer.createText(this._el_11,'\n    ',(null as any));
    this._text_36 = this.renderer.createText((null as any),'\n    \n\n    ',(null as any));
    this._text_37 = this.renderer.createText((null as any),'\n\n    ',(null as any));
    this._text_38 = this.renderer.createText((null as any),'\n',(null as any));
    compView_9.create(this._Content_9_4,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_10,
        this._el_11,
        this._text_36,
        this._text_37,
        this._text_38
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._expr_0 = import8.UNINITIALIZED;
    this._expr_1 = import8.UNINITIALIZED;
    this._expr_2 = import8.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_11,'ngSubmit',this.eventHandler(this._handle_ngSubmit_11_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_11,'submit',this.eventHandler(this._handle_submit_11_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_11,'reset',this.eventHandler(this._handle_reset_11_2.bind(this)));
    this._expr_6 = import8.UNINITIALIZED;
    const subscription_0:any = this._FormGroupDirective_11_3.ngSubmit.subscribe(this.eventHandler(this._handle_ngSubmit_11_0.bind(this)));
    this._expr_7 = import8.UNINITIALIZED;
    this._expr_8 = import8.UNINITIALIZED;
    this._expr_9 = import8.UNINITIALIZED;
    this._expr_10 = import8.UNINITIALIZED;
    this._expr_11 = import8.UNINITIALIZED;
    this._expr_12 = import8.UNINITIALIZED;
    this._expr_13 = import8.UNINITIALIZED;
    this._expr_14 = import8.UNINITIALIZED;
    this._expr_15 = import8.UNINITIALIZED;
    this._expr_16 = import8.UNINITIALIZED;
    this._expr_17 = import8.UNINITIALIZED;
    this._expr_18 = import8.UNINITIALIZED;
    this._expr_19 = import8.UNINITIALIZED;
    this._expr_20 = import8.UNINITIALIZED;
    this._expr_21 = import8.UNINITIALIZED;
    this._expr_22 = import8.UNINITIALIZED;
    this._expr_23 = import8.UNINITIALIZED;
    this._expr_24 = import8.UNINITIALIZED;
    this._expr_25 = import8.UNINITIALIZED;
    this._expr_26 = import8.UNINITIALIZED;
    this._expr_27 = import8.UNINITIALIZED;
    this._expr_28 = import8.UNINITIALIZED;
    this._expr_29 = import8.UNINITIALIZED;
    this._expr_30 = import8.UNINITIALIZED;
    this._expr_31 = import8.UNINITIALIZED;
    this._expr_32 = import8.UNINITIALIZED;
    this._expr_33 = import8.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_34,'click',this.eventHandler(this._handle_click_34_0.bind(this)));
    this._expr_35 = import8.UNINITIALIZED;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._text_36,
      this._text_37,
      this._text_38
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    ,[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.ToolbarTitle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._ToolbarTitle_4_4; }
    if (((token === import18.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Navbar_2_4; }
    if (((token === import17.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Header_0_3; }
    if (((token === import23.FormControlName) && (13 === requestNodeIndex))) { return this._FormControlName_13_4; }
    if (((token === import43.NgControl) && (13 === requestNodeIndex))) { return this._NgControl_13_5; }
    if (((token === import22.NgControlStatus) && (13 === requestNodeIndex))) { return this._NgControlStatus_13_6; }
    if (((token === import24.TextInput) && (13 === requestNodeIndex))) { return this._TextInput_13_7; }
    if (((token === import27.Label) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._Label_17_3; }
    if (((token === import23.FormControlName) && (20 === requestNodeIndex))) { return this._FormControlName_20_4; }
    if (((token === import43.NgControl) && (20 === requestNodeIndex))) { return this._NgControl_20_5; }
    if (((token === import22.NgControlStatus) && (20 === requestNodeIndex))) { return this._NgControlStatus_20_6; }
    if (((token === import24.TextInput) && (20 === requestNodeIndex))) { return this._TextInput_20_7; }
    if (((token === import25.Item) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._Item_15_4; }
    if (((token === import25.ItemContent) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._ItemContent_15_5; }
    if (((token === import27.Label) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._Label_25_3; }
    if (((token === import23.FormControlName) && (28 === requestNodeIndex))) { return this._FormControlName_28_4; }
    if (((token === import43.NgControl) && (28 === requestNodeIndex))) { return this._NgControl_28_5; }
    if (((token === import22.NgControlStatus) && (28 === requestNodeIndex))) { return this._NgControlStatus_28_6; }
    if (((token === import24.TextInput) && (28 === requestNodeIndex))) { return this._TextInput_28_7; }
    if (((token === import25.Item) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._Item_23_4; }
    if (((token === import25.ItemContent) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._ItemContent_23_5; }
    if (((token === import28.Button) && ((31 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._Button_31_4; }
    if (((token === import28.Button) && (34 === requestNodeIndex))) { return this._Button_34_4; }
    if (((token === import21.FormGroupDirective) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._FormGroupDirective_11_3; }
    if (((token === import44.ControlContainer) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._ControlContainer_11_4; }
    if (((token === import22.NgControlStatusGroup) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._NgControlStatusGroup_11_5; }
    if (((token === import20.Content) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 38)))) { return this._Content_9_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    var changes:{[key: string]:import8.SimpleChange} = (null as any);
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_9_4.ngOnInit(); }
    changes = (null as any);
    const currVal_6:any = this.context.myForm;
    if (import5.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._FormGroupDirective_11_3.form = currVal_6;
      if ((changes === (null as any))) { (changes = {}); }
      changes['form'] = new import8.SimpleChange(this._expr_6,currVal_6);
      this._expr_6 = currVal_6;
    }
    if ((changes !== (null as any))) { this._FormGroupDirective_11_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_13:any = 'id';
    if (import5.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this._FormControlName_13_4.name = currVal_13;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import8.SimpleChange(this._expr_13,currVal_13);
      this._expr_13 = currVal_13;
    }
    if ((changes !== (null as any))) { this._FormControlName_13_4.ngOnChanges(changes); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._TextInput_13_7.ngOnInit(); }
    changes = (null as any);
    const currVal_20:any = 'nombre';
    if (import5.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this._FormControlName_20_4.name = currVal_20;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import8.SimpleChange(this._expr_20,currVal_20);
      this._expr_20 = currVal_20;
    }
    if ((changes !== (null as any))) { this._FormControlName_20_4.ngOnChanges(changes); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._TextInput_20_7.ngOnInit(); }
    changes = (null as any);
    const currVal_27:any = 'telefono';
    if (import5.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this._FormControlName_28_4.name = currVal_27;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import8.SimpleChange(this._expr_27,currVal_27);
      this._expr_27 = currVal_27;
    }
    if ((changes !== (null as any))) { this._FormControlName_28_4.ngOnChanges(changes); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._TextInput_28_7.ngOnInit(); }
    changed = false;
    const currVal_35:any = 'danger';
    if (import5.checkBinding(throwOnChange,this._expr_35,currVal_35)) {
      this._Button_34_4.color = currVal_35;
      changed = true;
      this._expr_35 = currVal_35;
    }
    if (changed) { this._appEl_34.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_15_1.dirty) {
        this._query_Button_15_1.reset(([] as any[]));
        this._Item_15_4._buttons = this._query_Button_15_1;
        this._query_Button_15_1.notifyOnChanges();
      }
      if (this._query_Icon_15_2.dirty) {
        this._query_Icon_15_2.reset(([] as any[]));
        this._Item_15_4._icons = this._query_Icon_15_2;
        this._query_Icon_15_2.notifyOnChanges();
      }
      if (this._query_Button_23_1.dirty) {
        this._query_Button_23_1.reset(([] as any[]));
        this._Item_23_4._buttons = this._query_Button_23_1;
        this._query_Button_23_1.notifyOnChanges();
      }
      if (this._query_Icon_23_2.dirty) {
        this._query_Icon_23_2.reset(([] as any[]));
        this._Item_23_4._icons = this._query_Icon_23_2;
        this._query_Icon_23_2.notifyOnChanges();
      }
      this._TextInput_13_7.ngAfterContentChecked();
      this._TextInput_20_7.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_15_4.ngAfterContentInit(); }
      this._TextInput_28_7.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_23_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_31_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_34_4.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_2_4._hidden;
    if (import5.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4._sbPadding;
    if (import5.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Content_9_4._sbPadding;
    if (import5.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_9,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_7:any = this._NgControlStatusGroup_11_5.ngClassUntouched;
    if (import5.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_11,'ng-untouched',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatusGroup_11_5.ngClassTouched;
    if (import5.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_11,'ng-touched',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatusGroup_11_5.ngClassPristine;
    if (import5.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_11,'ng-pristine',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._NgControlStatusGroup_11_5.ngClassDirty;
    if (import5.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_11,'ng-dirty',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this._NgControlStatusGroup_11_5.ngClassValid;
    if (import5.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_11,'ng-valid',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this._NgControlStatusGroup_11_5.ngClassInvalid;
    if (import5.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_11,'ng-invalid',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_14:any = this._NgControlStatus_13_6.ngClassUntouched;
    if (import5.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_13,'ng-untouched',currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = this._NgControlStatus_13_6.ngClassTouched;
    if (import5.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_13,'ng-touched',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = this._NgControlStatus_13_6.ngClassPristine;
    if (import5.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_13,'ng-pristine',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = this._NgControlStatus_13_6.ngClassDirty;
    if (import5.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_13,'ng-dirty',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this._NgControlStatus_13_6.ngClassValid;
    if (import5.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_13,'ng-valid',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this._NgControlStatus_13_6.ngClassInvalid;
    if (import5.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_13,'ng-invalid',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_21:any = this._NgControlStatus_20_6.ngClassUntouched;
    if (import5.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setElementClass(this._el_20,'ng-untouched',currVal_21);
      this._expr_21 = currVal_21;
    }
    const currVal_22:any = this._NgControlStatus_20_6.ngClassTouched;
    if (import5.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setElementClass(this._el_20,'ng-touched',currVal_22);
      this._expr_22 = currVal_22;
    }
    const currVal_23:any = this._NgControlStatus_20_6.ngClassPristine;
    if (import5.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this.renderer.setElementClass(this._el_20,'ng-pristine',currVal_23);
      this._expr_23 = currVal_23;
    }
    const currVal_24:any = this._NgControlStatus_20_6.ngClassDirty;
    if (import5.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setElementClass(this._el_20,'ng-dirty',currVal_24);
      this._expr_24 = currVal_24;
    }
    const currVal_25:any = this._NgControlStatus_20_6.ngClassValid;
    if (import5.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setElementClass(this._el_20,'ng-valid',currVal_25);
      this._expr_25 = currVal_25;
    }
    const currVal_26:any = this._NgControlStatus_20_6.ngClassInvalid;
    if (import5.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this.renderer.setElementClass(this._el_20,'ng-invalid',currVal_26);
      this._expr_26 = currVal_26;
    }
    const currVal_28:any = this._NgControlStatus_28_6.ngClassUntouched;
    if (import5.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementClass(this._el_28,'ng-untouched',currVal_28);
      this._expr_28 = currVal_28;
    }
    const currVal_29:any = this._NgControlStatus_28_6.ngClassTouched;
    if (import5.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementClass(this._el_28,'ng-touched',currVal_29);
      this._expr_29 = currVal_29;
    }
    const currVal_30:any = this._NgControlStatus_28_6.ngClassPristine;
    if (import5.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this.renderer.setElementClass(this._el_28,'ng-pristine',currVal_30);
      this._expr_30 = currVal_30;
    }
    const currVal_31:any = this._NgControlStatus_28_6.ngClassDirty;
    if (import5.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this.renderer.setElementClass(this._el_28,'ng-dirty',currVal_31);
      this._expr_31 = currVal_31;
    }
    const currVal_32:any = this._NgControlStatus_28_6.ngClassValid;
    if (import5.checkBinding(throwOnChange,this._expr_32,currVal_32)) {
      this.renderer.setElementClass(this._el_28,'ng-valid',currVal_32);
      this._expr_32 = currVal_32;
    }
    const currVal_33:any = this._NgControlStatus_28_6.ngClassInvalid;
    if (import5.checkBinding(throwOnChange,this._expr_33,currVal_33)) {
      this.renderer.setElementClass(this._el_28,'ng-invalid',currVal_33);
      this._expr_33 = currVal_33;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._FormControlName_13_4.ngOnDestroy();
    this._TextInput_13_7.ngOnDestroy();
    this._FormControlName_20_4.ngOnDestroy();
    this._TextInput_20_7.ngOnDestroy();
    this._FormControlName_28_4.ngOnDestroy();
    this._TextInput_28_7.ngOnDestroy();
    this._Content_9_4.ngOnDestroy();
  }
  private _handle_ngSubmit_11_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onSubmit()) !== false);
    return (true && pd_0);
  }
  private _handle_submit_11_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._FormGroupDirective_11_3.onSubmit($event)) !== false);
    return (true && pd_0);
  }
  private _handle_reset_11_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._FormGroupDirective_11_3.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_click_34_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.cancelar()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_ClienteEditarComponent0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<import4.ClienteEditarComponent> {
  if ((renderType_ClienteEditarComponent === (null as any))) { (renderType_ClienteEditarComponent = viewUtils.createRenderComponentType('',0,import15.ViewEncapsulation.None,styles_ClienteEditarComponent,{})); }
  return new _View_ClienteEditarComponent0(viewUtils,parentInjector,declarationEl);
}